//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fenrir13.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Descriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Descriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fenrir13.Resources.Descriptions", typeof(Descriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du befindest Dich in Deinem persönlichen Raum des Schiffs. Er ist sehr funktional und spatanisch ausgestattet, wirkt dabei aber dennoch wohnlich. Der Cryo-Pod, in dem Du gerade noch gelegen hast, hat seine Kokon-Form, die dem Passagier während der langen Schlafphase einer Raumreise Schutz und Versorgung bietet, in eine offene Bettform gewandelt. Der Fußboden ist metallisch und nur vor Deinem Bett befindet sich ein kleiner Teppich. Du weißt aus der Ehfahrung, das der Fußboden angenehmt beheizt ist und magnet [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRYOCHAMBER {
            get {
                return ResourceManager.GetString("CRYOCHAMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalerweise kann man das Sichtfenster zum Schutz verschließen, doch aktuell ist er nicht aktiviert und es dringt der blinkende rote Schein der Alarmbeleuchtung durch das Glas und taucht Dein ansonsten halbdunkles Zimmer in einen gespenstigen Schimmer.
        ///Auch das Display blinkt rot und bedeutet Dir, alsbald einen Blick darauf zu werfen..
        /// </summary>
        internal static string CRYOCHAMBER_FIRSTLOOK {
            get {
                return ResourceManager.GetString("CRYOCHAMBER_FIRSTLOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schwarz. Langsam fräst sich ein auf- und abschwellendes Geräusch durch Deine vernebelten Sinne. Erst scheinbar fern, kommt es pulsierend näher. Ein roter Schein erscheint in der Dunkelheit. Ganz klein und schwach. Gleichermaßen näher kommend und subtil bedrohlich. Ein Tunnel? Ein Zug?
        ///Plötzlich zerreist ein stechender Schmerz in Deinen Lungen Deine Illusion. Adrenalien schiesst durch Deinen Körper und holt Dich mit voller, unbarmherziger Härte zurück ins Bewußtsein. Du reisst Deine Augen auf und wirst zugl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OPENING {
            get {
                return ResourceManager.GetString("OPENING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du bist eine smarte und gut aussehende Person. Du hast einen Abschluss in Geologie und in Exogeologie promoviert. Deine Aufgabe ist im Wesentlichen die Beurteilung der Qualität und Reinheit der seltenen Metalle wie Gold, Platin, Iridium und Rhenium, die während der Expedition abgebaut werden..
        /// </summary>
        internal static string PLAYER {
            get {
                return ResourceManager.GetString("PLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als Du an Dir herunter schaust stellst Du fest, dass Du nackt bist. Klar! Der Space-Suite würde die Schlaf im Cryo-Pod auch eher bedindern..
        /// </summary>
        internal static string PLAYER_FIRSTLOOK {
            get {
                return ResourceManager.GetString("PLAYER_FIRSTLOOK", resourceCulture);
            }
        }
    }
}
