//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fenrir13.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Descriptions {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Descriptions() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Fenrir13.Resources.Descriptions", typeof(Descriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string OPENING {
            get {
                return ResourceManager.GetString("OPENING", resourceCulture);
            }
        }
        
        internal static string CRYOCHAMBER {
            get {
                return ResourceManager.GetString("CRYOCHAMBER", resourceCulture);
            }
        }
        
        internal static string PLAYER {
            get {
                return ResourceManager.GetString("PLAYER", resourceCulture);
            }
        }
        
        internal static string PLAYER_FIRSTLOOK {
            get {
                return ResourceManager.GetString("PLAYER_FIRSTLOOK", resourceCulture);
            }
        }
        
        internal static string CRYOCHAMBER_FIRSTLOOK {
            get {
                return ResourceManager.GetString("CRYOCHAMBER_FIRSTLOOK", resourceCulture);
            }
        }
        
        internal static string CRYOPOD {
            get {
                return ResourceManager.GetString("CRYOPOD", resourceCulture);
            }
        }
        
        internal static string CHAMBER_FLOOR {
            get {
                return ResourceManager.GetString("CHAMBER_FLOOR", resourceCulture);
            }
        }
        
        internal static string WORKBENCH {
            get {
                return ResourceManager.GetString("WORKBENCH", resourceCulture);
            }
        }
        
        internal static string LAPTOP {
            get {
                return ResourceManager.GetString("LAPTOP", resourceCulture);
            }
        }
        
        internal static string CHAMBER_WALL {
            get {
                return ResourceManager.GetString("CHAMBER_WALL", resourceCulture);
            }
        }
        
        internal static string PIERHOLE {
            get {
                return ResourceManager.GetString("PIERHOLE", resourceCulture);
            }
        }
        
        internal static string OFFICECHAIR {
            get {
                return ResourceManager.GetString("OFFICECHAIR", resourceCulture);
            }
        }
        
        internal static string CLOSET {
            get {
                return ResourceManager.GetString("CLOSET", resourceCulture);
            }
        }
        
        internal static string DRAWER {
            get {
                return ResourceManager.GetString("DRAWER", resourceCulture);
            }
        }
        
        internal static string CLOSET_DOOR {
            get {
                return ResourceManager.GetString("CLOSET_DOOR", resourceCulture);
            }
        }
        
        internal static string CHOCOLATEBAR {
            get {
                return ResourceManager.GetString("CHOCOLATEBAR", resourceCulture);
            }
        }
        
        internal static string CHOCOLATEBAR_EATEN {
            get {
                return ResourceManager.GetString("CHOCOLATEBAR_EATEN", resourceCulture);
            }
        }
        
        internal static string WARDROBE {
            get {
                return ResourceManager.GetString("WARDROBE", resourceCulture);
            }
        }
        
        internal static string SPACE_SUIT {
            get {
                return ResourceManager.GetString("SPACE_SUIT", resourceCulture);
            }
        }
        
        internal static string SPACE_SUIT_TAKEN {
            get {
                return ResourceManager.GetString("SPACE_SUIT_TAKEN", resourceCulture);
            }
        }
        
        internal static string SPACE_SUIT_FIT {
            get {
                return ResourceManager.GetString("SPACE_SUIT_FIT", resourceCulture);
            }
        }
        
        internal static string TABLE {
            get {
                return ResourceManager.GetString("TABLE", resourceCulture);
            }
        }
        
        internal static string CHAIR {
            get {
                return ResourceManager.GetString("CHAIR", resourceCulture);
            }
        }
        
        internal static string PARTITION_WALL {
            get {
                return ResourceManager.GetString("PARTITION_WALL", resourceCulture);
            }
        }
        
        internal static string WASHINGAREA {
            get {
                return ResourceManager.GetString("WASHINGAREA", resourceCulture);
            }
        }
        
        internal static string TOILET {
            get {
                return ResourceManager.GetString("TOILET", resourceCulture);
            }
        }
        
        internal static string MIRROR {
            get {
                return ResourceManager.GetString("MIRROR", resourceCulture);
            }
        }
        
        internal static string OUTLINES {
            get {
                return ResourceManager.GetString("OUTLINES", resourceCulture);
            }
        }
        
        internal static string PEEPHOLE {
            get {
                return ResourceManager.GetString("PEEPHOLE", resourceCulture);
            }
        }
        
        internal static string LATCH {
            get {
                return ResourceManager.GetString("LATCH", resourceCulture);
            }
        }
        
        internal static string CRYOCHAMBER_DOOR {
            get {
                return ResourceManager.GetString("CRYOCHAMBER_DOOR", resourceCulture);
            }
        }
        
        internal static string DISPLAY {
            get {
                return ResourceManager.GetString("DISPLAY", resourceCulture);
            }
        }
        
        internal static string DISPLAY_BAR_EATEN {
            get {
                return ResourceManager.GetString("DISPLAY_BAR_EATEN", resourceCulture);
            }
        }
        
        internal static string INTERVENTION_REQUIRED {
            get {
                return ResourceManager.GetString("INTERVENTION_REQUIRED", resourceCulture);
            }
        }
        
        internal static string DISPLAY_BAR_NOT_EATEN {
            get {
                return ResourceManager.GetString("DISPLAY_BAR_NOT_EATEN", resourceCulture);
            }
        }
        
        internal static string CLOSET_DOOR_FIRSTLOOK {
            get {
                return ResourceManager.GetString("CLOSET_DOOR_FIRSTLOOK", resourceCulture);
            }
        }
        
        internal static string TOILET_SEAT {
            get {
                return ResourceManager.GetString("TOILET_SEAT", resourceCulture);
            }
        }
        
        internal static string INTERVENTION_REQUIRED_INTERPRETATION {
            get {
                return ResourceManager.GetString("INTERVENTION_REQUIRED_INTERPRETATION", resourceCulture);
            }
        }
        
        internal static string CORRIDOR_EAST {
            get {
                return ResourceManager.GetString("CORRIDOR_EAST", resourceCulture);
            }
        }
        
        internal static string CORRIDOR_EAST_LOCKDESCRIPTION {
            get {
                return ResourceManager.GetString("CORRIDOR_EAST_LOCKDESCRIPTION", resourceCulture);
            }
        }
        
        internal static string CANT_LEAVE_CHAMBER {
            get {
                return ResourceManager.GetString("CANT_LEAVE_CHAMBER", resourceCulture);
            }
        }
        
        internal static string CORRIDOR_WEST {
            get {
                return ResourceManager.GetString("CORRIDOR_WEST", resourceCulture);
            }
        }
        
        internal static string CORRIDOR_MIDEAST {
            get {
                return ResourceManager.GetString("CORRIDOR_MIDEAST", resourceCulture);
            }
        }
        
        internal static string CORRIDOR_MID {
            get {
                return ResourceManager.GetString("CORRIDOR_MID", resourceCulture);
            }
        }
        
        internal static string CORRIDOR_MIDWEST {
            get {
                return ResourceManager.GetString("CORRIDOR_MIDWEST", resourceCulture);
            }
        }
        
        internal static string EMPTYCREWCHAMBERONE {
            get {
                return ResourceManager.GetString("EMPTYCREWCHAMBERONE", resourceCulture);
            }
        }
        
        internal static string EMPTYCREWCHAMBER_LOCKDESCRIPTION {
            get {
                return ResourceManager.GetString("EMPTYCREWCHAMBER_LOCKDESCRIPTION", resourceCulture);
            }
        }
        
        internal static string EMPTYCREWCHAMBERTWO {
            get {
                return ResourceManager.GetString("EMPTYCREWCHAMBERTWO", resourceCulture);
            }
        }
        
        internal static string CORRIDOR_WEST_LOCKDESCRIPTION {
            get {
                return ResourceManager.GetString("CORRIDOR_WEST_LOCKDESCRIPTION", resourceCulture);
            }
        }
        
        internal static string BULKHEAD {
            get {
                return ResourceManager.GetString("BULKHEAD", resourceCulture);
            }
        }
        
        internal static string BULKHEAD_WINDOW {
            get {
                return ResourceManager.GetString("BULKHEAD_WINDOW", resourceCulture);
            }
        }
        
        internal static string TERMINAL_PASSWORD_HINT {
            get {
                return ResourceManager.GetString("TERMINAL_PASSWORD_HINT", resourceCulture);
            }
        }
        
        internal static string COMMANDBRIDGE {
            get {
                return ResourceManager.GetString("COMMANDBRIDGE", resourceCulture);
            }
        }
        
        internal static string COMMANDBRIDGE_FIRSTLOOK {
            get {
                return ResourceManager.GetString("COMMANDBRIDGE_FIRSTLOOK", resourceCulture);
            }
        }
        
        internal static string CRYOCHAMBER_DOOR_TRY_OPEN {
            get {
                return ResourceManager.GetString("CRYOCHAMBER_DOOR_TRY_OPEN", resourceCulture);
            }
        }
        
        internal static string PILOT_SEAT {
            get {
                return ResourceManager.GetString("PILOT_SEAT", resourceCulture);
            }
        }
        
        internal static string CORRIDOR_PAINTING_EAST {
            get {
                return ResourceManager.GetString("CORRIDOR_PAINTING_EAST", resourceCulture);
            }
        }
        
        internal static string CORRIDOR_PAINTING_MIDEAST {
            get {
                return ResourceManager.GetString("CORRIDOR_PAINTING_MIDEAST", resourceCulture);
            }
        }
        
        internal static string PORTRAIT {
            get {
                return ResourceManager.GetString("PORTRAIT", resourceCulture);
            }
        }
        
        internal static string COMPUTER_TERMINAL {
            get {
                return ResourceManager.GetString("COMPUTER_TERMINAL", resourceCulture);
            }
        }
        
        internal static string COMPUTER_TERMINAL_FIRSTLOOK {
            get {
                return ResourceManager.GetString("COMPUTER_TERMINAL_FIRSTLOOK", resourceCulture);
            }
        }
        
        internal static string TERMINAL_PASSWORD {
            get {
                return ResourceManager.GetString("TERMINAL_PASSWORD", resourceCulture);
            }
        }
        
        internal static string STICKY_NOTE {
            get {
                return ResourceManager.GetString("STICKY_NOTE", resourceCulture);
            }
        }
        
        internal static string CONTROL_PANEL {
            get {
                return ResourceManager.GetString("CONTROL_PANEL", resourceCulture);
            }
        }
        
        internal static string STICKY_NOTE_FOUND {
            get {
                return ResourceManager.GetString("STICKY_NOTE_FOUND", resourceCulture);
            }
        }
        
        internal static string TERMINAL_PASSWORD_WRONG {
            get {
                return ResourceManager.GetString("TERMINAL_PASSWORD_WRONG", resourceCulture);
            }
        }
        
        internal static string COMPUTER_TERMINAL_DISPLAY_PASSWORD {
            get {
                return ResourceManager.GetString("COMPUTER_TERMINAL_DISPLAY_PASSWORD", resourceCulture);
            }
        }
        
        internal static string OVOID {
            get {
                return ResourceManager.GetString("OVOID", resourceCulture);
            }
        }
        
        internal static string FRONTSIDE {
            get {
                return ResourceManager.GetString("FRONTSIDE", resourceCulture);
            }
        }
        
        internal static string FRONTWINDOW {
            get {
                return ResourceManager.GetString("FRONTWINDOW", resourceCulture);
            }
        }
        
        internal static string CONTROL_PANEL_CONTENT {
            get {
                return ResourceManager.GetString("CONTROL_PANEL_CONTENT", resourceCulture);
            }
        }
        
        internal static string NECESSITIES {
            get {
                return ResourceManager.GetString("NECESSITIES", resourceCulture);
            }
        }
        
        internal static string PERSONAL_SETTINGS {
            get {
                return ResourceManager.GetString("PERSONAL_SETTINGS", resourceCulture);
            }
        }
        
        internal static string COMPUTER_TERMINAL_DISPLAY_REPORT {
            get {
                return ResourceManager.GetString("COMPUTER_TERMINAL_DISPLAY_REPORT", resourceCulture);
            }
        }
        
        internal static string TERMINAL_PASSWORD_SUCCESS {
            get {
                return ResourceManager.GetString("TERMINAL_PASSWORD_SUCCESS", resourceCulture);
            }
        }
        
        internal static string TERMINAL_PASSWORD_HINT_WRONG {
            get {
                return ResourceManager.GetString("TERMINAL_PASSWORD_HINT_WRONG", resourceCulture);
            }
        }
        
        internal static string COMPUTER_TERMINAL_DISPLAY_REPORT_1 {
            get {
                return ResourceManager.GetString("COMPUTER_TERMINAL_DISPLAY_REPORT_1", resourceCulture);
            }
        }
        
        internal static string TERMINAL_MENU_1 {
            get {
                return ResourceManager.GetString("TERMINAL_MENU_1", resourceCulture);
            }
        }
        
        internal static string TERMINAL_MENU_2 {
            get {
                return ResourceManager.GetString("TERMINAL_MENU_2", resourceCulture);
            }
        }
        
        internal static string COMPUTER_TERMINAL_DISPLAY_REPORT_2 {
            get {
                return ResourceManager.GetString("COMPUTER_TERMINAL_DISPLAY_REPORT_2", resourceCulture);
            }
        }
        
        internal static string MACHINE_CORRIDOR_MID {
            get {
                return ResourceManager.GetString("MACHINE_CORRIDOR_MID", resourceCulture);
            }
        }
        
        internal static string MACHINE_CORRIDOR_MID_LOCKDESCRIPTION {
            get {
                return ResourceManager.GetString("MACHINE_CORRIDOR_MID_LOCKDESCRIPTION", resourceCulture);
            }
        }
        
        internal static string CORRIDOR_PAINTING_WEST {
            get {
                return ResourceManager.GetString("CORRIDOR_PAINTING_WEST", resourceCulture);
            }
        }
        
        internal static string CORRIDOR_PAINTING_MIDWEST {
            get {
                return ResourceManager.GetString("CORRIDOR_PAINTING_MIDWEST", resourceCulture);
            }
        }
        
        internal static string GYM {
            get {
                return ResourceManager.GetString("GYM", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM {
            get {
                return ResourceManager.GetString("SOCIALROOM", resourceCulture);
            }
        }
        
        internal static string KITCHEN {
            get {
                return ResourceManager.GetString("KITCHEN", resourceCulture);
            }
        }
        
        internal static string AIRLOCK {
            get {
                return ResourceManager.GetString("AIRLOCK", resourceCulture);
            }
        }
        
        internal static string ENGINE_ROOM {
            get {
                return ResourceManager.GetString("ENGINE_ROOM", resourceCulture);
            }
        }
        
        internal static string CARDIO_STATION {
            get {
                return ResourceManager.GetString("CARDIO_STATION", resourceCulture);
            }
        }
        
        internal static string GYM_POWERSTATION {
            get {
                return ResourceManager.GetString("GYM_POWERSTATION", resourceCulture);
            }
        }
        
        internal static string DUMBBELL_BAR {
            get {
                return ResourceManager.GetString("DUMBBELL_BAR", resourceCulture);
            }
        }
        
        internal static string DUMBBELL_RACK {
            get {
                return ResourceManager.GetString("DUMBBELL_RACK", resourceCulture);
            }
        }
        
        internal static string EXERCISE_AREA {
            get {
                return ResourceManager.GetString("EXERCISE_AREA", resourceCulture);
            }
        }
        
        internal static string GYM_FLOSKEL {
            get {
                return ResourceManager.GetString("GYM_FLOSKEL", resourceCulture);
            }
        }
        
        internal static string FITNESSMACHINE {
            get {
                return ResourceManager.GetString("FITNESSMACHINE", resourceCulture);
            }
        }
        
        internal static string WORKOUTS {
            get {
                return ResourceManager.GetString("WORKOUTS", resourceCulture);
            }
        }
        
        internal static string DUMBBELL_BAR_CONTAINMENT {
            get {
                return ResourceManager.GetString("DUMBBELL_BAR_CONTAINMENT", resourceCulture);
            }
        }
        
        internal static string SPACE_SUIT_CONTAINMENT {
            get {
                return ResourceManager.GetString("SPACE_SUIT_CONTAINMENT", resourceCulture);
            }
        }
        
        internal static string EQUIPMENT_ROOM {
            get {
                return ResourceManager.GetString("EQUIPMENT_ROOM", resourceCulture);
            }
        }
        
        internal static string EQUIPMENT_BOX {
            get {
                return ResourceManager.GetString("EQUIPMENT_BOX", resourceCulture);
            }
        }
        
        internal static string EQUIPMENT_BOX_CONTAINMENT {
            get {
                return ResourceManager.GetString("EQUIPMENT_BOX_CONTAINMENT", resourceCulture);
            }
        }
        
        internal static string HELMET {
            get {
                return ResourceManager.GetString("HELMET", resourceCulture);
            }
        }
        
        internal static string HELMET_FIRSTLOOK {
            get {
                return ResourceManager.GetString("HELMET_FIRSTLOOK", resourceCulture);
            }
        }
        
        internal static string GLOVES {
            get {
                return ResourceManager.GetString("GLOVES", resourceCulture);
            }
        }
        
        internal static string BOOTS {
            get {
                return ResourceManager.GetString("BOOTS", resourceCulture);
            }
        }
        
        internal static string EQUIPMENT_BOX_LOCK {
            get {
                return ResourceManager.GetString("EQUIPMENT_BOX_LOCK", resourceCulture);
            }
        }
        
        internal static string BREAK_EQUIPMENT_BOX_LOCK {
            get {
                return ResourceManager.GetString("BREAK_EQUIPMENT_BOX_LOCK", resourceCulture);
            }
        }
        
        internal static string EQUIPMENT_BOX_CLOSED {
            get {
                return ResourceManager.GetString("EQUIPMENT_BOX_CLOSED", resourceCulture);
            }
        }
        
        internal static string AIRLOCK_KEYPAD {
            get {
                return ResourceManager.GetString("AIRLOCK_KEYPAD", resourceCulture);
            }
        }
        
        internal static string AIRLOCK_KEYPAD_RED_BUTTON {
            get {
                return ResourceManager.GetString("AIRLOCK_KEYPAD_RED_BUTTON", resourceCulture);
            }
        }
        
        internal static string AIRLOCK_KEYPAD_GREEN_BUTTON {
            get {
                return ResourceManager.GetString("AIRLOCK_KEYPAD_GREEN_BUTTON", resourceCulture);
            }
        }
        
        internal static string EQUIPMENT_ROOM_BENCH {
            get {
                return ResourceManager.GetString("EQUIPMENT_ROOM_BENCH", resourceCulture);
            }
        }
        
        internal static string EQUIPMENT_ROOM_NICHE {
            get {
                return ResourceManager.GetString("EQUIPMENT_ROOM_NICHE", resourceCulture);
            }
        }
        
        internal static string EQUIPMENT_ROOM_TRASHBIN {
            get {
                return ResourceManager.GetString("EQUIPMENT_ROOM_TRASHBIN", resourceCulture);
            }
        }
        
        internal static string EQUIPMENT_ROOM_CLOTH {
            get {
                return ResourceManager.GetString("EQUIPMENT_ROOM_CLOTH", resourceCulture);
            }
        }
        
        internal static string ZERO_GRAVITY {
            get {
                return ResourceManager.GetString("ZERO_GRAVITY", resourceCulture);
            }
        }
        
        internal static string GRAVITY_NORMAL {
            get {
                return ResourceManager.GetString("GRAVITY_NORMAL", resourceCulture);
            }
        }
        
        internal static string BELT {
            get {
                return ResourceManager.GetString("BELT", resourceCulture);
            }
        }
        
        internal static string GRAVITY_ITEM_DROP {
            get {
                return ResourceManager.GetString("GRAVITY_ITEM_DROP", resourceCulture);
            }
        }
        
        internal static string WRITING_MATERIALS {
            get {
                return ResourceManager.GetString("WRITING_MATERIALS", resourceCulture);
            }
        }
        
        internal static string CORRIDOR_DESTINATION {
            get {
                return ResourceManager.GetString("CORRIDOR_DESTINATION", resourceCulture);
            }
        }
        
        internal static string EMPTYCREWCHAMBERONE_DESTINATION {
            get {
                return ResourceManager.GetString("EMPTYCREWCHAMBERONE_DESTINATION", resourceCulture);
            }
        }
        
        internal static string BRIDGE_DESTINATION {
            get {
                return ResourceManager.GetString("BRIDGE_DESTINATION", resourceCulture);
            }
        }
        
        internal static string COMMANDBRIDGE_TO_CORRIDOR_DESTINATION {
            get {
                return ResourceManager.GetString("COMMANDBRIDGE_TO_CORRIDOR_DESTINATION", resourceCulture);
            }
        }
        
        internal static string AMBULANCE {
            get {
                return ResourceManager.GetString("AMBULANCE", resourceCulture);
            }
        }
        
        internal static string AMBULANCE_OP_TABLE {
            get {
                return ResourceManager.GetString("AMBULANCE_OP_TABLE", resourceCulture);
            }
        }
        
        internal static string AMBULANCE_OP_ROBOTER {
            get {
                return ResourceManager.GetString("AMBULANCE_OP_ROBOTER", resourceCulture);
            }
        }
        
        internal static string CEILING {
            get {
                return ResourceManager.GetString("CEILING", resourceCulture);
            }
        }
        
        internal static string AMBULANCE_BED {
            get {
                return ResourceManager.GetString("AMBULANCE_BED", resourceCulture);
            }
        }
        
        internal static string AMBULANCE_OP_ITEMS {
            get {
                return ResourceManager.GetString("AMBULANCE_OP_ITEMS", resourceCulture);
            }
        }
        
        internal static string AMBULANCE_MEDIS {
            get {
                return ResourceManager.GetString("AMBULANCE_MEDIS", resourceCulture);
            }
        }
        
        internal static string AMBULANCE_RESPIRATOR {
            get {
                return ResourceManager.GetString("AMBULANCE_RESPIRATOR", resourceCulture);
            }
        }
        
        internal static string AMBULANCE_RESPIRATOR_FLAP {
            get {
                return ResourceManager.GetString("AMBULANCE_RESPIRATOR_FLAP", resourceCulture);
            }
        }
        
        internal static string AMBULANCE_RESPIRATOR_FLAP_LOCK {
            get {
                return ResourceManager.GetString("AMBULANCE_RESPIRATOR_FLAP_LOCK", resourceCulture);
            }
        }
        
        internal static string AMBULANCE_RESPIRATOR_FLAP_FIRSTLOOK {
            get {
                return ResourceManager.GetString("AMBULANCE_RESPIRATOR_FLAP_FIRSTLOOK", resourceCulture);
            }
        }
        
        internal static string AMBULANCE_RESPIRATOR_FLAP_DUMBBELL_BAR_UNBREAKABLE {
            get {
                return ResourceManager.GetString("AMBULANCE_RESPIRATOR_FLAP_DUMBBELL_BAR_UNBREAKABLE", resourceCulture);
            }
        }
        
        internal static string FRIDGE {
            get {
                return ResourceManager.GetString("FRIDGE", resourceCulture);
            }
        }
        
        internal static string FOOD_PRINTER {
            get {
                return ResourceManager.GetString("FOOD_PRINTER", resourceCulture);
            }
        }
        
        internal static string FOOD_PRINTER_OPEN {
            get {
                return ResourceManager.GetString("FOOD_PRINTER_OPEN", resourceCulture);
            }
        }
        
        internal static string FRIDGE_DOOR_HANDLE {
            get {
                return ResourceManager.GetString("FRIDGE_DOOR_HANDLE", resourceCulture);
            }
        }
        
        internal static string FRIDGE_DOOR_HANDLE_OPEN {
            get {
                return ResourceManager.GetString("FRIDGE_DOOR_HANDLE_OPEN", resourceCulture);
            }
        }
        
        internal static string FOOD_PRINTER_CLOSE {
            get {
                return ResourceManager.GetString("FOOD_PRINTER_CLOSE", resourceCulture);
            }
        }
        
        internal static string FRIDGE_CLOSE {
            get {
                return ResourceManager.GetString("FRIDGE_CLOSE", resourceCulture);
            }
        }
        
        internal static string FRIDGE_DOOR_HANDLE_PULL {
            get {
                return ResourceManager.GetString("FRIDGE_DOOR_HANDLE_PULL", resourceCulture);
            }
        }
        
        internal static string FRIDGE_DOOR_HANDLE_CONTAINMENT {
            get {
                return ResourceManager.GetString("FRIDGE_DOOR_HANDLE_CONTAINMENT", resourceCulture);
            }
        }
        
        internal static string FRIDGE_OPEN {
            get {
                return ResourceManager.GetString("FRIDGE_OPEN", resourceCulture);
            }
        }
        
        internal static string FRIDGE_DOOR_HANDLE_UNPICKABLE {
            get {
                return ResourceManager.GetString("FRIDGE_DOOR_HANDLE_UNPICKABLE", resourceCulture);
            }
        }
        
        internal static string FRIDGE_LOCKED {
            get {
                return ResourceManager.GetString("FRIDGE_LOCKED", resourceCulture);
            }
        }
        
        internal static string RECYCLER {
            get {
                return ResourceManager.GetString("RECYCLER", resourceCulture);
            }
        }
        
        internal static string RECYCLER_FIRSTLOOK {
            get {
                return ResourceManager.GetString("RECYCLER_FIRSTLOOK", resourceCulture);
            }
        }
        
        internal static string EQUIPMENT_BOX_LOCK_CONTAINMENT {
            get {
                return ResourceManager.GetString("EQUIPMENT_BOX_LOCK_CONTAINMENT", resourceCulture);
            }
        }
        
        internal static string EQUIPMENT_BOX_LOCK_BREAK_CONTAINMENT {
            get {
                return ResourceManager.GetString("EQUIPMENT_BOX_LOCK_BREAK_CONTAINMENT", resourceCulture);
            }
        }
        
        internal static string EQUIPMENT_BOX_LOCK_DESTROYED {
            get {
                return ResourceManager.GetString("EQUIPMENT_BOX_LOCK_DESTROYED", resourceCulture);
            }
        }
        
        internal static string EQUIPMENT_BOX_FIRSTLOOK {
            get {
                return ResourceManager.GetString("EQUIPMENT_BOX_FIRSTLOOK", resourceCulture);
            }
        }
        
        internal static string FRIDGE_DOOR_HANDLE_PUSHED {
            get {
                return ResourceManager.GetString("FRIDGE_DOOR_HANDLE_PUSHED", resourceCulture);
            }
        }
        
        internal static string FRIDGE_DOOR_HANDLE_FLAP_LINKEDTO {
            get {
                return ResourceManager.GetString("FRIDGE_DOOR_HANDLE_FLAP_LINKEDTO", resourceCulture);
            }
        }
        
        internal static string FRIDGE_DOOR_HANDLE_FLAP_UNPICKABLE {
            get {
                return ResourceManager.GetString("FRIDGE_DOOR_HANDLE_FLAP_UNPICKABLE", resourceCulture);
            }
        }
        
        internal static string OXYGEN_BOTTLE {
            get {
                return ResourceManager.GetString("OXYGEN_BOTTLE", resourceCulture);
            }
        }
        
        internal static string OXYGEN_BOTTLE_FIRSTLOOK {
            get {
                return ResourceManager.GetString("OXYGEN_BOTTLE_FIRSTLOOK", resourceCulture);
            }
        }
        
        internal static string AMBULANCE_RESPIRATOR_FLAP_CONTAINMENT {
            get {
                return ResourceManager.GetString("AMBULANCE_RESPIRATOR_FLAP_CONTAINMENT", resourceCulture);
            }
        }
        
        internal static string AMBULANCE_OP_ITEMS_DETAIL {
            get {
                return ResourceManager.GetString("AMBULANCE_OP_ITEMS_DETAIL", resourceCulture);
            }
        }
        
        internal static string OXYGEN_BOTTLE_FOUND {
            get {
                return ResourceManager.GetString("OXYGEN_BOTTLE_FOUND", resourceCulture);
            }
        }
        
        internal static string SPACE_SUIT_UNDROPABLE {
            get {
                return ResourceManager.GetString("SPACE_SUIT_UNDROPABLE", resourceCulture);
            }
        }
        
        internal static string LINK_OXYGEN_BOTTLE_TO_HELMET {
            get {
                return ResourceManager.GetString("LINK_OXYGEN_BOTTLE_TO_HELMET", resourceCulture);
            }
        }
        
        internal static string CRYOCHAMBER_BULKHEAD {
            get {
                return ResourceManager.GetString("CRYOCHAMBER_BULKHEAD", resourceCulture);
            }
        }
        
        internal static string AIRLOCK_KEYPAD_CONTAINMENT {
            get {
                return ResourceManager.GetString("AIRLOCK_KEYPAD_CONTAINMENT", resourceCulture);
            }
        }
        
        internal static string AIRLOCK_ROPE {
            get {
                return ResourceManager.GetString("AIRLOCK_ROPE", resourceCulture);
            }
        }
        
        internal static string AIRLOCK_CABLE_WINCH {
            get {
                return ResourceManager.GetString("AIRLOCK_CABLE_WINCH", resourceCulture);
            }
        }
        
        internal static string AIRLOCK_CABLE_WINCH_CONTAINMENT {
            get {
                return ResourceManager.GetString("AIRLOCK_CABLE_WINCH_CONTAINMENT", resourceCulture);
            }
        }
        
        internal static string AIRLOCK_ROPE_CONTAINMENT {
            get {
                return ResourceManager.GetString("AIRLOCK_ROPE_CONTAINMENT", resourceCulture);
            }
        }
        
        internal static string AIRLOCK_ROPE_LINKEDTO {
            get {
                return ResourceManager.GetString("AIRLOCK_ROPE_LINKEDTO", resourceCulture);
            }
        }
        
        internal static string OXYGEN_NEEDED {
            get {
                return ResourceManager.GetString("OXYGEN_NEEDED", resourceCulture);
            }
        }
        
        internal static string SPACE_CLOTHS_NEEDED {
            get {
                return ResourceManager.GetString("SPACE_CLOTHS_NEEDED", resourceCulture);
            }
        }
        
        internal static string PREPARED_FOR_SPACE_WALK {
            get {
                return ResourceManager.GetString("PREPARED_FOR_SPACE_WALK", resourceCulture);
            }
        }
        
        internal static string LINK_ROPE_TO_EYELET {
            get {
                return ResourceManager.GetString("LINK_ROPE_TO_EYELET", resourceCulture);
            }
        }
        
        internal static string AIRLOCK_NORTHERN_WALL {
            get {
                return ResourceManager.GetString("AIRLOCK_NORTHERN_WALL", resourceCulture);
            }
        }
        
        internal static string AIRLOCK_SOUTHERN_WALL {
            get {
                return ResourceManager.GetString("AIRLOCK_SOUTHERN_WALL", resourceCulture);
            }
        }
        
        internal static string SAFETY_FIRST {
            get {
                return ResourceManager.GetString("SAFETY_FIRST", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_COUCH {
            get {
                return ResourceManager.GetString("SOCIALROOM_COUCH", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_MONITOR {
            get {
                return ResourceManager.GetString("SOCIALROOM_MONITOR", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_SEAT {
            get {
                return ResourceManager.GetString("SOCIALROOM_SEAT", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_EAST_WEST_WALL {
            get {
                return ResourceManager.GetString("SOCIALROOM_EAST_WEST_WALL", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_CEILING {
            get {
                return ResourceManager.GetString("SOCIALROOM_CEILING", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_ANTENNA_CONSTRUCTION {
            get {
                return ResourceManager.GetString("SOCIALROOM_ANTENNA_CONSTRUCTION", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_ANTENNA_CONSTRUCTION_CONTAINMENT {
            get {
                return ResourceManager.GetString("SOCIALROOM_ANTENNA_CONSTRUCTION_CONTAINMENT", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_ANTENNA {
            get {
                return ResourceManager.GetString("SOCIALROOM_ANTENNA", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_ANTENNA_LINKEDTODESCRIPTION {
            get {
                return ResourceManager.GetString("SOCIALROOM_ANTENNA_LINKEDTODESCRIPTION", resourceCulture);
            }
        }
        
        internal static string CANT_REACH_ANTENNA {
            get {
                return ResourceManager.GetString("CANT_REACH_ANTENNA", resourceCulture);
            }
        }
        
        internal static string CANT_TAKE_ANTENNA {
            get {
                return ResourceManager.GetString("CANT_TAKE_ANTENNA", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_BOOKS {
            get {
                return ResourceManager.GetString("SOCIALROOM_BOOKS", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_SEATGROUP {
            get {
                return ResourceManager.GetString("SOCIALROOM_SEATGROUP", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_BOOK_I {
            get {
                return ResourceManager.GetString("SOCIALROOM_BOOK_I", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_BOOK_II {
            get {
                return ResourceManager.GetString("SOCIALROOM_BOOK_II", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_BOOK_III {
            get {
                return ResourceManager.GetString("SOCIALROOM_BOOK_III", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_BOOK_IV {
            get {
                return ResourceManager.GetString("SOCIALROOM_BOOK_IV", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_BOOK_V {
            get {
                return ResourceManager.GetString("SOCIALROOM_BOOK_V", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_BOOK_VI {
            get {
                return ResourceManager.GetString("SOCIALROOM_BOOK_VI", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_BOOK_VII {
            get {
                return ResourceManager.GetString("SOCIALROOM_BOOK_VII", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_BOOK_VIII {
            get {
                return ResourceManager.GetString("SOCIALROOM_BOOK_VIII", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_BOOK_IX {
            get {
                return ResourceManager.GetString("SOCIALROOM_BOOK_IX", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_BOOK_X {
            get {
                return ResourceManager.GetString("SOCIALROOM_BOOK_X", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_WALL {
            get {
                return ResourceManager.GetString("SOCIALROOM_WALL", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_SOUTH_WALL {
            get {
                return ResourceManager.GetString("SOCIALROOM_SOUTH_WALL", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_NORTH_WALL {
            get {
                return ResourceManager.GetString("SOCIALROOM_NORTH_WALL", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_BILLARD {
            get {
                return ResourceManager.GetString("SOCIALROOM_BILLARD", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_DARTS {
            get {
                return ResourceManager.GetString("SOCIALROOM_DARTS", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_BILLARD_THINGS {
            get {
                return ResourceManager.GetString("SOCIALROOM_BILLARD_THINGS", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_BILLARD_CUE {
            get {
                return ResourceManager.GetString("SOCIALROOM_BILLARD_CUE", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_BILLARD_CHALK {
            get {
                return ResourceManager.GetString("SOCIALROOM_BILLARD_CHALK", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_BILLARD_BRUSH {
            get {
                return ResourceManager.GetString("SOCIALROOM_BILLARD_BRUSH", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_BILLARD_TRIANGLE {
            get {
                return ResourceManager.GetString("SOCIALROOM_BILLARD_TRIANGLE", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_BILLARD_BALLS {
            get {
                return ResourceManager.GetString("SOCIALROOM_BILLARD_BALLS", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_GLASS_TABLE {
            get {
                return ResourceManager.GetString("SOCIALROOM_GLASS_TABLE", resourceCulture);
            }
        }
        
        internal static string FRIDGE_DOOR_HANDLE_DROP {
            get {
                return ResourceManager.GetString("FRIDGE_DOOR_HANDLE_DROP", resourceCulture);
            }
        }
        
        internal static string ENGINE_ROOM_SHIP_MODEL_CONTAINMENT {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_SHIP_MODEL_CONTAINMENT", resourceCulture);
            }
        }
        
        internal static string ENGINE_ROOM_SHIP_MODEL {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_SHIP_MODEL", resourceCulture);
            }
        }
        
        internal static string ENGINE_ROOM_RED_DOTS {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_RED_DOTS", resourceCulture);
            }
        }
        
        internal static string ENGINE_ROOM_ART {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_ART", resourceCulture);
            }
        }
        
        internal static string ENGINE_ROOM_TECHNIC {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_TECHNIC", resourceCulture);
            }
        }
        
        internal static string ENGINE_ROOM_STEALING {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_STEALING", resourceCulture);
            }
        }
        
        internal static string ENGINE_ROOM_HEAD {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_HEAD", resourceCulture);
            }
        }
        
        internal static string ENGINE_ROOM_TANGENT {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_TANGENT", resourceCulture);
            }
        }
        
        internal static string ENGINE_ROOM_COMPUTER {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_COMPUTER", resourceCulture);
            }
        }
        
        internal static string MAINTENANCE_ROOM {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM", resourceCulture);
            }
        }
        
        internal static string MAINTENANCE_ROOM_DRAWER {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_DRAWER", resourceCulture);
            }
        }
        
        internal static string MAINTENANCE_ROOM_TOOL {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_TOOL", resourceCulture);
            }
        }
        
        internal static string MAINTENANCE_ROOM_WORKBENCH {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_WORKBENCH", resourceCulture);
            }
        }
        
        internal static string MAINTENANCE_ROOM_DRAWER_CONTAINMENT {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_DRAWER_CONTAINMENT", resourceCulture);
            }
        }
        
        internal static string MAINTENANCE_ROOM_TOOL_CONTAINMENT {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_TOOL_CONTAINMENT", resourceCulture);
            }
        }
        
        internal static string MAINTENANCE_ROOM_DRAWER_CLOSE {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_DRAWER_CLOSE", resourceCulture);
            }
        }
        
        internal static string MAINTENANCE_ROOM_DRAWER_OPEN {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_DRAWER_OPEN", resourceCulture);
            }
        }
        
        internal static string GET_ANTENNA {
            get {
                return ResourceManager.GetString("GET_ANTENNA", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_ANTENNA_CONSTRUCTION_WITHOUT_ANTENNA {
            get {
                return ResourceManager.GetString("SOCIALROOM_ANTENNA_CONSTRUCTION_WITHOUT_ANTENNA", resourceCulture);
            }
        }
        
        internal static string JETTY {
            get {
                return ResourceManager.GetString("JETTY", resourceCulture);
            }
        }
        
        internal static string CANT_LEAVE_AIRLOCK {
            get {
                return ResourceManager.GetString("CANT_LEAVE_AIRLOCK", resourceCulture);
            }
        }
        
        internal static string CANT_LEAVE_OPEN_AIRLOCK {
            get {
                return ResourceManager.GetString("CANT_LEAVE_OPEN_AIRLOCK", resourceCulture);
            }
        }
        
        internal static string PRESS_GREEN_BUTTON {
            get {
                return ResourceManager.GetString("PRESS_GREEN_BUTTON", resourceCulture);
            }
        }
        
        internal static string CANT_LEAVE_WITH_TIED_EYELET {
            get {
                return ResourceManager.GetString("CANT_LEAVE_WITH_TIED_EYELET", resourceCulture);
            }
        }
        
        internal static string AIRLOCK_OPEN_DROP_CLOTHES {
            get {
                return ResourceManager.GetString("AIRLOCK_OPEN_DROP_CLOTHES", resourceCulture);
            }
        }
        
        internal static string ROOF_TOP {
            get {
                return ResourceManager.GetString("ROOF_TOP", resourceCulture);
            }
        }
        
        internal static string ROOF_TOP_DESTINATION {
            get {
                return ResourceManager.GetString("ROOF_TOP_DESTINATION", resourceCulture);
            }
        }
        
        internal static string DROID {
            get {
                return ResourceManager.GetString("DROID", resourceCulture);
            }
        }
        
        internal static string DROID_FIRSTLOOK {
            get {
                return ResourceManager.GetString("DROID_FIRSTLOOK", resourceCulture);
            }
        }
        
        internal static string DROID_ANTENNA_LINKDESCRIPTION {
            get {
                return ResourceManager.GetString("DROID_ANTENNA_LINKDESCRIPTION", resourceCulture);
            }
        }
        
        internal static string DROID_ANTENNE_UNPICKABLE {
            get {
                return ResourceManager.GetString("DROID_ANTENNE_UNPICKABLE", resourceCulture);
            }
        }
        
        internal static string DROID_ANTENNA_MOUNTED {
            get {
                return ResourceManager.GetString("DROID_ANTENNA_MOUNTED", resourceCulture);
            }
        }
        
        internal static string MAINTENANCE_ROOM_TOOL_NOT_PRESENT {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_TOOL_NOT_PRESENT", resourceCulture);
            }
        }
        
        internal static string PANEL_TOP {
            get {
                return ResourceManager.GetString("PANEL_TOP", resourceCulture);
            }
        }
        
        internal static string PANEL_TOP_LEVER {
            get {
                return ResourceManager.GetString("PANEL_TOP_LEVER", resourceCulture);
            }
        }
        
        internal static string PANEL_TOP_LEVER_CONTAINMENT {
            get {
                return ResourceManager.GetString("PANEL_TOP_LEVER_CONTAINMENT", resourceCulture);
            }
        }
        
        internal static string PANEL_TOP_LEVER_PULL {
            get {
                return ResourceManager.GetString("PANEL_TOP_LEVER_PULL", resourceCulture);
            }
        }
        
        internal static string PANEL_TOP_LEVER_DUMBBELL_BAR {
            get {
                return ResourceManager.GetString("PANEL_TOP_LEVER_DUMBBELL_BAR", resourceCulture);
            }
        }
        
        internal static string PANEL_TOP_LEVER_REDDOTS_CONTAINMENT {
            get {
                return ResourceManager.GetString("PANEL_TOP_LEVER_REDDOTS_CONTAINMENT", resourceCulture);
            }
        }
        
        internal static string DROID_ENERGY_CONTAINMENT {
            get {
                return ResourceManager.GetString("DROID_ENERGY_CONTAINMENT", resourceCulture);
            }
        }
        
        internal static string GOODBYE {
            get {
                return ResourceManager.GetString("GOODBYE", resourceCulture);
            }
        }
        
        internal static string CLOSING {
            get {
                return ResourceManager.GetString("CLOSING", resourceCulture);
            }
        }
        
        internal static string CRYOCHAMBER_LAMP {
            get {
                return ResourceManager.GetString("CRYOCHAMBER_LAMP", resourceCulture);
            }
        }
        
        internal static string CRYOCHAMBER_CLOTHS {
            get {
                return ResourceManager.GetString("CRYOCHAMBER_CLOTHS", resourceCulture);
            }
        }
        
        internal static string PROXIMA_CENTAURI {
            get {
                return ResourceManager.GetString("PROXIMA_CENTAURI", resourceCulture);
            }
        }
        
        internal static string CORRIDOR_WALLS {
            get {
                return ResourceManager.GetString("CORRIDOR_WALLS", resourceCulture);
            }
        }
        
        internal static string PAPER {
            get {
                return ResourceManager.GetString("PAPER", resourceCulture);
            }
        }
        
        internal static string PENCILS {
            get {
                return ResourceManager.GetString("PENCILS", resourceCulture);
            }
        }
        
        internal static string PENCIL_I {
            get {
                return ResourceManager.GetString("PENCIL_I", resourceCulture);
            }
        }
        
        internal static string PENCIL_II {
            get {
                return ResourceManager.GetString("PENCIL_II", resourceCulture);
            }
        }
        
        internal static string WHERE_TO_SIT {
            get {
                return ResourceManager.GetString("WHERE_TO_SIT", resourceCulture);
            }
        }
        
        internal static string TRY_TO_SIT_ON_CHAIR {
            get {
                return ResourceManager.GetString("TRY_TO_SIT_ON_CHAIR", resourceCulture);
            }
        }
        
        internal static string TRY_TO_SIT_ON_OFFICECHAIR {
            get {
                return ResourceManager.GetString("TRY_TO_SIT_ON_OFFICECHAIR", resourceCulture);
            }
        }
        
        internal static string TRY_TO_TAKE_LAPTOP {
            get {
                return ResourceManager.GetString("TRY_TO_TAKE_LAPTOP", resourceCulture);
            }
        }
        
        internal static string WEIGHT_PLATES {
            get {
                return ResourceManager.GetString("WEIGHT_PLATES", resourceCulture);
            }
        }
        
        internal static string GYM_ROPES {
            get {
                return ResourceManager.GetString("GYM_ROPES", resourceCulture);
            }
        }
        
        internal static string GYM_ROPES_NO_PICKUP {
            get {
                return ResourceManager.GetString("GYM_ROPES_NO_PICKUP", resourceCulture);
            }
        }
        
        internal static string GYM_BRACKET {
            get {
                return ResourceManager.GetString("GYM_BRACKET", resourceCulture);
            }
        }
        
        internal static string GYM_SANDBAG {
            get {
                return ResourceManager.GetString("GYM_SANDBAG", resourceCulture);
            }
        }
        
        internal static string GYM_SANDBAG_NO_PICKUP {
            get {
                return ResourceManager.GetString("GYM_SANDBAG_NO_PICKUP", resourceCulture);
            }
        }
        
        internal static string GYM_LOOP {
            get {
                return ResourceManager.GetString("GYM_LOOP", resourceCulture);
            }
        }
        
        internal static string FELT {
            get {
                return ResourceManager.GetString("FELT", resourceCulture);
            }
        }
        
        internal static string HOLE {
            get {
                return ResourceManager.GetString("HOLE", resourceCulture);
            }
        }
        
        internal static string SIDEWALL {
            get {
                return ResourceManager.GetString("SIDEWALL", resourceCulture);
            }
        }
        
        internal static string CREWCHAMBERS {
            get {
                return ResourceManager.GetString("CREWCHAMBERS", resourceCulture);
            }
        }
        
        internal static string LINK_OXYGEN_BOTTLE_TO_HELMET_WITH_HELMET_ON {
            get {
                return ResourceManager.GetString("LINK_OXYGEN_BOTTLE_TO_HELMET_WITH_HELMET_ON", resourceCulture);
            }
        }
        
        internal static string RED_DOT {
            get {
                return ResourceManager.GetString("RED_DOT", resourceCulture);
            }
        }
        
        internal static string LOCATION {
            get {
                return ResourceManager.GetString("LOCATION", resourceCulture);
            }
        }
        
        internal static string GREEN_ARROWS {
            get {
                return ResourceManager.GetString("GREEN_ARROWS", resourceCulture);
            }
        }
        
        internal static string EMERGENCY_LIGHT {
            get {
                return ResourceManager.GetString("EMERGENCY_LIGHT", resourceCulture);
            }
        }
        
        internal static string CREW_DOORS {
            get {
                return ResourceManager.GetString("CREW_DOORS", resourceCulture);
            }
        }
        
        internal static string ROOM_DOOR {
            get {
                return ResourceManager.GetString("ROOM_DOOR", resourceCulture);
            }
        }
        
        internal static string ROUND_STAIRS {
            get {
                return ResourceManager.GetString("ROUND_STAIRS", resourceCulture);
            }
        }
        
        internal static string STAIRS {
            get {
                return ResourceManager.GetString("STAIRS", resourceCulture);
            }
        }
        
        internal static string MACHINE_DESTINATION {
            get {
                return ResourceManager.GetString("MACHINE_DESTINATION", resourceCulture);
            }
        }
        
        internal static string CORRIDOR_MID_DESTINATION {
            get {
                return ResourceManager.GetString("CORRIDOR_MID_DESTINATION", resourceCulture);
            }
        }
        
        internal static string AIRLOCK_DESTINATION {
            get {
                return ResourceManager.GetString("AIRLOCK_DESTINATION", resourceCulture);
            }
        }
        
        internal static string ENGINE_ROOM_DESTINATION {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_DESTINATION", resourceCulture);
            }
        }
        
        internal static string MAINTENANCE_ROOM_EAST_WALL {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_EAST_WALL", resourceCulture);
            }
        }
        
        internal static string MAINTENANCE_ROOM_SHELF {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_SHELF", resourceCulture);
            }
        }
        
        internal static string MAINTENANCE_ROOM_PLATE {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_PLATE", resourceCulture);
            }
        }
        
        internal static string SIGNS_OF_USE {
            get {
                return ResourceManager.GetString("SIGNS_OF_USE", resourceCulture);
            }
        }
        
        internal static string MAINTENANCE_ROOM_DRAWER_HANDLE {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_DRAWER_HANDLE", resourceCulture);
            }
        }
        
        internal static string ENGINE_ROOM_SHIP_MODEL_CONTAINMENT_II {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_SHIP_MODEL_CONTAINMENT_II", resourceCulture);
            }
        }
        
        internal static string ENGINE_ROOM_RED_DOTS_NO_ROBOT {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_RED_DOTS_NO_ROBOT", resourceCulture);
            }
        }
        
        internal static string ENGINE_ROOM_RED_DOTS_NO_SOLAR {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_RED_DOTS_NO_SOLAR", resourceCulture);
            }
        }
        
        internal static string CORRIDOR_WEST_FIRSTLOOK {
            get {
                return ResourceManager.GetString("CORRIDOR_WEST_FIRSTLOOK", resourceCulture);
            }
        }
        
        internal static string CORRIDOR_WEST_HOLE {
            get {
                return ResourceManager.GetString("CORRIDOR_WEST_HOLE", resourceCulture);
            }
        }
        
        internal static string CORRIDOR_WEST_WELD_SEAM {
            get {
                return ResourceManager.GetString("CORRIDOR_WEST_WELD_SEAM", resourceCulture);
            }
        }
        
        internal static string CORRIDOR_WEST_BULLEYE {
            get {
                return ResourceManager.GetString("CORRIDOR_WEST_BULLEYE", resourceCulture);
            }
        }
        
        internal static string RETURN_TO_BRIDGE {
            get {
                return ResourceManager.GetString("RETURN_TO_BRIDGE", resourceCulture);
            }
        }
        
        internal static string ROBOT_FIXING_WALL {
            get {
                return ResourceManager.GetString("ROBOT_FIXING_WALL", resourceCulture);
            }
        }
        
        internal static string TRY_TO_SIT_ON_COUCH {
            get {
                return ResourceManager.GetString("TRY_TO_SIT_ON_COUCH", resourceCulture);
            }
        }
        
        internal static string TRY_TO_SIT_ON_SEAT {
            get {
                return ResourceManager.GetString("TRY_TO_SIT_ON_SEAT", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_MEDIASERVER {
            get {
                return ResourceManager.GetString("SOCIALROOM_MEDIASERVER", resourceCulture);
            }
        }
        
        internal static string KITCHEN_CABINET {
            get {
                return ResourceManager.GetString("KITCHEN_CABINET", resourceCulture);
            }
        }
        
        internal static string PANEL_TOP_SUPPLYLINES {
            get {
                return ResourceManager.GetString("PANEL_TOP_SUPPLYLINES", resourceCulture);
            }
        }
        
        internal static string PANEL_TOP_WOLF {
            get {
                return ResourceManager.GetString("PANEL_TOP_WOLF", resourceCulture);
            }
        }
        
        internal static string PANEL_TOP_LAMPS {
            get {
                return ResourceManager.GetString("PANEL_TOP_LAMPS", resourceCulture);
            }
        }
        
        internal static string PANEL_TOP_WINDOWS {
            get {
                return ResourceManager.GetString("PANEL_TOP_WINDOWS", resourceCulture);
            }
        }
        
        internal static string PANEL_TOP_PANELS {
            get {
                return ResourceManager.GetString("PANEL_TOP_PANELS", resourceCulture);
            }
        }
        
        internal static string PANEL_TOP_WAY_TO_JETTY {
            get {
                return ResourceManager.GetString("PANEL_TOP_WAY_TO_JETTY", resourceCulture);
            }
        }
        
        internal static string SPACE_LADDER {
            get {
                return ResourceManager.GetString("SPACE_LADDER", resourceCulture);
            }
        }
        
        internal static string ROOF_TOP_WAY_TO_JETTY {
            get {
                return ResourceManager.GetString("ROOF_TOP_WAY_TO_JETTY", resourceCulture);
            }
        }
        
        internal static string JETTY_HULL {
            get {
                return ResourceManager.GetString("JETTY_HULL", resourceCulture);
            }
        }
        
        internal static string JETTY_SPACE {
            get {
                return ResourceManager.GetString("JETTY_SPACE", resourceCulture);
            }
        }
        
        internal static string JETTY_ENGINE {
            get {
                return ResourceManager.GetString("JETTY_ENGINE", resourceCulture);
            }
        }
        
        internal static string AIRLOCK_BULKHEAD {
            get {
                return ResourceManager.GetString("AIRLOCK_BULKHEAD", resourceCulture);
            }
        }
        
        internal static string DROID_FIRSTLOOK_II {
            get {
                return ResourceManager.GetString("DROID_FIRSTLOOK_II", resourceCulture);
            }
        }
        
        internal static string ROOF_TOP_DOCK {
            get {
                return ResourceManager.GetString("ROOF_TOP_DOCK", resourceCulture);
            }
        }
        
        internal static string ROOF_TOP_CLAW {
            get {
                return ResourceManager.GetString("ROOF_TOP_CLAW", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM_CANT_REACH_RECEIVER_FROM_HERE {
            get {
                return ResourceManager.GetString("SOCIALROOM_CANT_REACH_RECEIVER_FROM_HERE", resourceCulture);
            }
        }
        
        internal static string KITCHEN_FOOD_BAG {
            get {
                return ResourceManager.GetString("KITCHEN_FOOD_BAG", resourceCulture);
            }
        }
        
        internal static string AMBULANCE_OXYGEN_HOSE {
            get {
                return ResourceManager.GetString("AMBULANCE_OXYGEN_HOSE", resourceCulture);
            }
        }
        
        internal static string TRY_TO_SIT_ON_GLASS_TABLE {
            get {
                return ResourceManager.GetString("TRY_TO_SIT_ON_GLASS_TABLE", resourceCulture);
            }
        }
        
        internal static string TRY_TO_SIT_ON_BILLARD_TABLE {
            get {
                return ResourceManager.GetString("TRY_TO_SIT_ON_BILLARD_TABLE", resourceCulture);
            }
        }
        
        internal static string QUATUM_CUBE {
            get {
                return ResourceManager.GetString("QUATUM_CUBE", resourceCulture);
            }
        }
        
        internal static string AMBULANCE_MEDIS_CABINET {
            get {
                return ResourceManager.GetString("AMBULANCE_MEDIS_CABINET", resourceCulture);
            }
        }
        
        internal static string CLIMBING_FRAME {
            get {
                return ResourceManager.GetString("CLIMBING_FRAME", resourceCulture);
            }
        }
        
        internal static string MAINTENANCE_ROOM_UTILS {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_UTILS", resourceCulture);
            }
        }
        
        internal static string JETTY_ALPHA {
            get {
                return ResourceManager.GetString("JETTY_ALPHA", resourceCulture);
            }
        }
        
        internal static string UNIVERSE {
            get {
                return ResourceManager.GetString("UNIVERSE", resourceCulture);
            }
        }
        
        internal static string STARS {
            get {
                return ResourceManager.GetString("STARS", resourceCulture);
            }
        }
        
        internal static string MIRROR_FIRSTLOOK {
            get {
                return ResourceManager.GetString("MIRROR_FIRSTLOOK", resourceCulture);
            }
        }
        
        internal static string ITEM_NOT_EATABLE {
            get {
                return ResourceManager.GetString("ITEM_NOT_EATABLE", resourceCulture);
            }
        }
        
        internal static string GYM_IMPOSSIBLE_TRAINING {
            get {
                return ResourceManager.GetString("GYM_IMPOSSIBLE_TRAINING", resourceCulture);
            }
        }
        
        internal static string GYM_IMPOSSIBLE_RIDE {
            get {
                return ResourceManager.GetString("GYM_IMPOSSIBLE_RIDE", resourceCulture);
            }
        }
        
        internal static string ROPE_SKIPPING {
            get {
                return ResourceManager.GetString("ROPE_SKIPPING", resourceCulture);
            }
        }
        
        internal static string PORTRAIT_TO_HEAVY {
            get {
                return ResourceManager.GetString("PORTRAIT_TO_HEAVY", resourceCulture);
            }
        }
        
        internal static string AMBULANCE_RESPIRATOR_CONTAINMENT {
            get {
                return ResourceManager.GetString("AMBULANCE_RESPIRATOR_CONTAINMENT", resourceCulture);
            }
        }
        
        internal static string TURN_SHIP_MODEL {
            get {
                return ResourceManager.GetString("TURN_SHIP_MODEL", resourceCulture);
            }
        }
        
        internal static string ITEM_NOT_SCREWABLE {
            get {
                return ResourceManager.GetString("ITEM_NOT_SCREWABLE", resourceCulture);
            }
        }
        
        internal static string ITEM_NOT_SCREW_ON_ABLE {
            get {
                return ResourceManager.GetString("ITEM_NOT_SCREW_ON_ABLE", resourceCulture);
            }
        }
        
        internal static string ITEM_NOT_LEVERABLE {
            get {
                return ResourceManager.GetString("ITEM_NOT_LEVERABLE", resourceCulture);
            }
        }
    }
}
