//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fenrir13.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Items {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Items() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fenrir13.Resources.Items", typeof(Items).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teppich|Läufer.
        /// </summary>
        internal static string CARPET {
            get {
                return ResourceManager.GetString("CARPET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stuhl.
        /// </summary>
        internal static string CHAIR {
            get {
                return ResourceManager.GetString("CHAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fußboden|Fussboden|Boden.
        /// </summary>
        internal static string CHAMBER_FLOOR {
            get {
                return ResourceManager.GetString("CHAMBER_FLOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wand|Zimmerwand.
        /// </summary>
        internal static string CHAMBER_WALL {
            get {
                return ResourceManager.GetString("CHAMBER_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Power-Riegel|Power-Riegel|Powerriegel|Schokoladen-Riegel|Schokoladenriegel|Schoko-Riegel|Schokoriegel|Riegel.
        /// </summary>
        internal static string CHOCOLATEBAR {
            get {
                return ResourceManager.GetString("CHOCOLATEBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schrank|Kleiderschrank.
        /// </summary>
        internal static string CLOSET {
            get {
                return ResourceManager.GetString("CLOSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schranktür|Kleiderschranktür.
        /// </summary>
        internal static string CLOSET_DOOR {
            get {
                return ResourceManager.GetString("CLOSET_DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zimmertür|Tür.
        /// </summary>
        internal static string CRYOCHAMBER_DOOR {
            get {
                return ResourceManager.GetString("CRYOCHAMBER_DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryopod|Cryo-Pod|Bett|Schlafplatz|Schlafkammer|Pod.
        /// </summary>
        internal static string CRYOPOD {
            get {
                return ResourceManager.GetString("CRYOPOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display|Anzeige.
        /// </summary>
        internal static string DISPLAY {
            get {
                return ResourceManager.GetString("DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schublade|Schubfach|Schubfächer.
        /// </summary>
        internal static string DRAWER {
            get {
                return ResourceManager.GetString("DRAWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAPTOP|Rechner|Computer.
        /// </summary>
        internal static string LAPTOP {
            get {
                return ResourceManager.GetString("LAPTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klinke|Türklinke|Türgriff.
        /// </summary>
        internal static string LATCH {
            get {
                return ResourceManager.GetString("LATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiegel.
        /// </summary>
        internal static string MIRROR {
            get {
                return ResourceManager.GetString("MIRROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bürostuhl|Arbeitsstuhl|Sitzgelegenheit.
        /// </summary>
        internal static string OFFICECHAIR {
            get {
                return ResourceManager.GetString("OFFICECHAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umrisse|Umriss|Umriß.
        /// </summary>
        internal static string OUTLINES {
            get {
                return ResourceManager.GetString("OUTLINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trennwand|Sichtschutz.
        /// </summary>
        internal static string PARTITION_WALL {
            get {
                return ResourceManager.GetString("PARTITION_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guckloch.
        /// </summary>
        internal static string PEEPHOLE {
            get {
                return ResourceManager.GetString("PEEPHOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullauge|Fenster|Weltraum|All|Weltall.
        /// </summary>
        internal static string PIERHOLE {
            get {
                return ResourceManager.GetString("PIERHOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metallrollen|Rollen|Stuhlrollen|Gummi|Gummirollen.
        /// </summary>
        internal static string RUBBER_ROLLS {
            get {
                return ResourceManager.GetString("RUBBER_ROLLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Space-Overall|Space-Overall|Spaceoverall|Space-Suite|Spacesuite|Overall.
        /// </summary>
        internal static string SPACE_SUITE {
            get {
                return ResourceManager.GetString("SPACE_SUITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tisch.
        /// </summary>
        internal static string TABLE {
            get {
                return ResourceManager.GetString("TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toilette|Klo|Pott|Thron.
        /// </summary>
        internal static string TOILET {
            get {
                return ResourceManager.GetString("TOILET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toilettensitz|Klobrille|Klositz|WC-Sitz.
        /// </summary>
        internal static string TOILET_SEAT {
            get {
                return ResourceManager.GetString("TOILET_SEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Garderobe|Garderobe.
        /// </summary>
        internal static string WARDROBE {
            get {
                return ResourceManager.GetString("WARDROBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waschmöglichkeit|Waschbereich|Bad|Badezimmer|Waschbecken.
        /// </summary>
        internal static string WASHINGAREA {
            get {
                return ResourceManager.GetString("WASHINGAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitsbereich|Arbeitsplatz|Schreibtisch.
        /// </summary>
        internal static string WORKBENCH {
            get {
                return ResourceManager.GetString("WORKBENCH", resourceCulture);
            }
        }
    }
}
