//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fenrir13.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Items {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Items() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fenrir13.Resources.Items", typeof(Items).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Seilwinde|Seilwinde|Seil|Winde.
        /// </summary>
        internal static string AIRLOCK_CABLE_WINCH {
            get {
                return ResourceManager.GetString("AIRLOCK_CABLE_WINCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Tastenfeld|Tastenfeld|Tastatur.
        /// </summary>
        internal static string AIRLOCK_KEYPAD {
            get {
                return ResourceManager.GetString("AIRLOCK_KEYPAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der grüne Knopf|Grüner Knopf|Grünen Knopf|Grüne Taste.
        /// </summary>
        internal static string AIRLOCK_KEYPAD_GREEN_BUTTON {
            get {
                return ResourceManager.GetString("AIRLOCK_KEYPAD_GREEN_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der rote Knopf|Roter Knopf|Roten Knopf|Rote Taste.
        /// </summary>
        internal static string AIRLOCK_KEYPAD_RED_BUTTON {
            get {
                return ResourceManager.GetString("AIRLOCK_KEYPAD_RED_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die nördliche Wand|Nördliche Wand.
        /// </summary>
        internal static string AIRLOCK_NORTHERN_WALL {
            get {
                return ResourceManager.GetString("AIRLOCK_NORTHERN_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Graphen-Seil|Graphen-Seil|Seil.
        /// </summary>
        internal static string AIRLOCK_ROPE {
            get {
                return ResourceManager.GetString("AIRLOCK_ROPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die südliche Wand|Südliche Wand.
        /// </summary>
        internal static string AIRLOCK_SOUTHERN_WALL {
            get {
                return ResourceManager.GetString("AIRLOCK_SOUTHERN_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Krankenbett|Krankenbett|Krankenhausbett|Bett|Pflegebett.
        /// </summary>
        internal static string AMBULANCE_BED {
            get {
                return ResourceManager.GetString("AMBULANCE_BED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Medizinschrank|Medizinschrank|Medischrank|Medikamente|Medikament|Medis|Schrank.
        /// </summary>
        internal static string AMBULANCE_MEDIS {
            get {
                return ResourceManager.GetString("AMBULANCE_MEDIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die OP-Schränke|OP-Schränke| OP Schränke|OP-Schrank|OP Schrank|Das Verbandszeug|Verbandszeug|Verbandszeuge|Die Instrumente|Instrumente|Instrument|OP-Besteck.
        /// </summary>
        internal static string AMBULANCE_OP_ITEMS {
            get {
                return ResourceManager.GetString("AMBULANCE_OP_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Skalpell|Skalpell|Skalpelle|Der Tupfer|Tupfer|Die Mullbinde|Mullbinde|Mullbinden|Der Adapter|Adapter.
        /// </summary>
        internal static string AMBULANCE_OP_ITEMS_DETAIL {
            get {
                return ResourceManager.GetString("AMBULANCE_OP_ITEMS_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der OP-Roboter|OP-Roboter| OP Roboter|Roboter|Arm|Arme|vier Arme.
        /// </summary>
        internal static string AMBULANCE_OP_ROBOTER {
            get {
                return ResourceManager.GetString("AMBULANCE_OP_ROBOTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der OP-Tisch|OP-Tisch|OP Tisch|Tisch|Liegefläche|Tischplatte.
        /// </summary>
        internal static string AMBULANCE_OP_TABLE {
            get {
                return ResourceManager.GetString("AMBULANCE_OP_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Beatmungsgerät|Beatmungsgerät|Beatmungsmaschine|Beatmung|Beatmungsapparat|Gerät.
        /// </summary>
        internal static string AMBULANCE_RESPIRATOR {
            get {
                return ResourceManager.GetString("AMBULANCE_RESPIRATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Verschlussklappe|Verschlussklappe|Verschlusskappe|Klappe|Kappe.
        /// </summary>
        internal static string AMBULANCE_RESPIRATOR_FLAP {
            get {
                return ResourceManager.GetString("AMBULANCE_RESPIRATOR_FLAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Sicherungsgurt|Sicherungsgurt|Gurt|Geschirr|Sicherungsgeschirr.
        /// </summary>
        internal static string BELT {
            get {
                return ResourceManager.GetString("BELT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Fahrrad|Fahrrad|Rad.
        /// </summary>
        internal static string BIKE {
            get {
                return ResourceManager.GetString("BIKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Stiefel|Stiefel|Moonboots|Boots.
        /// </summary>
        internal static string BOOTS {
            get {
                return ResourceManager.GetString("BOOTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Schott|Schott|Abriegelung.
        /// </summary>
        internal static string BULKHEAD {
            get {
                return ResourceManager.GetString("BULKHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Sichtfenster|Sichtfenster.
        /// </summary>
        internal static string BULKHEAD_WINDOW {
            get {
                return ResourceManager.GetString("BULKHEAD_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Cardiostation|Cardiostation|Cardio.
        /// </summary>
        internal static string CARDIO_STATION {
            get {
                return ResourceManager.GetString("CARDIO_STATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Teppich|Teppich|Läufer.
        /// </summary>
        internal static string CARPET {
            get {
                return ResourceManager.GetString("CARPET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Zimmerdecke|Zimmerdecke|Decke.
        /// </summary>
        internal static string CEILING {
            get {
                return ResourceManager.GetString("CEILING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Stuhl|Stuhl|Stühle.
        /// </summary>
        internal static string CHAIR {
            get {
                return ResourceManager.GetString("CHAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Fußboden|Fußboden|Fussboden|Boden.
        /// </summary>
        internal static string CHAMBER_FLOOR {
            get {
                return ResourceManager.GetString("CHAMBER_FLOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Wand|Wand|Zimmerwand|Wände|Zimmerwände|Raumwand|Raumwände.
        /// </summary>
        internal static string CHAMBER_WALL {
            get {
                return ResourceManager.GetString("CHAMBER_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Power-Riegel|Power-Riegel|Powerriegel|Schokoladen-Riegel|Schokoladenriegel|Schoko-Riegel|Schokoriegel|Riegel.
        /// </summary>
        internal static string CHOCOLATEBAR {
            get {
                return ResourceManager.GetString("CHOCOLATEBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Schrank|Schrank|Kleiderschrank.
        /// </summary>
        internal static string CLOSET {
            get {
                return ResourceManager.GetString("CLOSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Schranktür|Schranktür|Kleiderschranktür.
        /// </summary>
        internal static string CLOSET_DOOR {
            get {
                return ResourceManager.GetString("CLOSET_DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedienkonsole|Konsole|Steuerpult|Pult|Platte|Glasplatte|Halbrund.
        /// </summary>
        internal static string CONTROL_PANEL {
            get {
                return ResourceManager.GetString("CONTROL_PANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrumente|Bilder|Informationstexte|Daten.
        /// </summary>
        internal static string CONTROL_PANEL_CONTENT {
            get {
                return ResourceManager.GetString("CONTROL_PANEL_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild|Bilder|Plakat|Poster.
        /// </summary>
        internal static string CORRIDOR_PAINTING {
            get {
                return ResourceManager.GetString("CORRIDOR_PAINTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Cross-Trainer|Cross-Trainer|Crosstrainer.
        /// </summary>
        internal static string CROSSTRAINER {
            get {
                return ResourceManager.GetString("CROSSTRAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Sichtfenster|Sichtfenster.
        /// </summary>
        internal static string CRYOCHAMBER_BULKHEAD {
            get {
                return ResourceManager.GetString("CRYOCHAMBER_BULKHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zimmertür|Tür.
        /// </summary>
        internal static string CRYOCHAMBER_DOOR {
            get {
                return ResourceManager.GetString("CRYOCHAMBER_DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryopod|Cryo-Pod|Bett|Schlafplatz|Schlafkammer|Pod|Kokon.
        /// </summary>
        internal static string CRYOPOD {
            get {
                return ResourceManager.GetString("CRYOPOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display|Anzeige.
        /// </summary>
        internal static string DISPLAY {
            get {
                return ResourceManager.GetString("DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schublade|Schubladen|Schubfach|Schubfächer|Fächer.
        /// </summary>
        internal static string DRAWER {
            get {
                return ResourceManager.GetString("DRAWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Hantelstange|Hantelstange|Stange|Hantel.
        /// </summary>
        internal static string DUMBBELL_BAR {
            get {
                return ResourceManager.GetString("DUMBBELL_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Hantelablage|Hantelablage|Ablage.
        /// </summary>
        internal static string DUMBBELL_RACK {
            get {
                return ResourceManager.GetString("DUMBBELL_RACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crew-Kammer-1|Crew-Kammer1|Kammer-1|Kammer1|Crew-Raum 1|Crew-Raum1|Raum-1|Raum1.
        /// </summary>
        internal static string EMPTYCREWCHAMBERONE {
            get {
                return ResourceManager.GetString("EMPTYCREWCHAMBERONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crew-Kammer-2|Crew-Kammer2|Kammer-2|Kammer2|Crew-Raum 2|Crew-Raum2|Raum-2|Raum2.
        /// </summary>
        internal static string EMPTYCREWCHAMBERTWO {
            get {
                return ResourceManager.GetString("EMPTYCREWCHAMBERTWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Metallkiste|Metallkiste|Ausrüstungsbox|Ausrüstungsbox|Box|Kiste.
        /// </summary>
        internal static string EQUIPMENT_BOX {
            get {
                return ResourceManager.GetString("EQUIPMENT_BOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Vorhängeschloss|Vorhängeschloss|Schloss|Schloß.
        /// </summary>
        internal static string EQUIPMENT_BOX_LOCK {
            get {
                return ResourceManager.GetString("EQUIPMENT_BOX_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Vorhängeschloss|Vorhängeschloss|Schloss|Schloß.
        /// </summary>
        internal static string EQUIPMENT_BOX_LOCK_DESTROYED {
            get {
                return ResourceManager.GetString("EQUIPMENT_BOX_LOCK_DESTROYED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Sitzbänke|Sitzbänke|Sitzbank|Bänke|Bank|Ausstattung.
        /// </summary>
        internal static string EQUIPMENT_ROOM_BENCH {
            get {
                return ResourceManager.GetString("EQUIPMENT_ROOM_BENCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Kleidungsstücke|Kleidungsstücke|Kleidung.
        /// </summary>
        internal static string EQUIPMENT_ROOM_CLOTH {
            get {
                return ResourceManager.GetString("EQUIPMENT_ROOM_CLOTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Nische|Nische|Wandnische|Nischen|Wandnischen.
        /// </summary>
        internal static string EQUIPMENT_ROOM_NICHE {
            get {
                return ResourceManager.GetString("EQUIPMENT_ROOM_NICHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Mülleimer|Mülleimer|Papiereimer|Papierkorb|Müllkorb|Abfalleimer|Abfallkorb|Korb|Eimer.
        /// </summary>
        internal static string EQUIPMENT_ROOM_TRASHBIN {
            get {
                return ResourceManager.GetString("EQUIPMENT_ROOM_TRASHBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Gymnastikbereich|Gymnastikbereich.
        /// </summary>
        internal static string EXERCISE_AREA {
            get {
                return ResourceManager.GetString("EXERCISE_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Öse|Öse.
        /// </summary>
        internal static string EYELET {
            get {
                return ResourceManager.GetString("EYELET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Fitnessmaschinen|Fitnessmaschinen|Fitnessmaschine|Geräte|Plätze|Plätzen.
        /// </summary>
        internal static string FITNESSMACHINE {
            get {
                return ResourceManager.GetString("FITNESSMACHINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Food-Printer|Food-Printer|FoodPrinter|Foot Printer|Printer|Drucker.
        /// </summary>
        internal static string FOOD_PRINTER {
            get {
                return ResourceManager.GetString("FOOD_PRINTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Kühlschrank|Kühlschrank.
        /// </summary>
        internal static string FRIDGE {
            get {
                return ResourceManager.GetString("FRIDGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Türgriff|Türgriff|Griff.
        /// </summary>
        internal static string FRIDGE_DOOR_HANDLE {
            get {
                return ResourceManager.GetString("FRIDGE_DOOR_HANDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frontseite|Front.
        /// </summary>
        internal static string FRONTSIDE {
            get {
                return ResourceManager.GetString("FRONTSIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRONTWINDOW.
        /// </summary>
        internal static string FRONTWINDOW {
            get {
                return ResourceManager.GetString("FRONTWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Handschuhe|Handschuhe|Handschuh.
        /// </summary>
        internal static string GLOVES {
            get {
                return ResourceManager.GetString("GLOVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Powerstation|Powerstation|Gewichte|Gewicht.
        /// </summary>
        internal static string GYM_POWERSTATION {
            get {
                return ResourceManager.GetString("GYM_POWERSTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Weltraumhelm|Weltraumhelm|Helm.
        /// </summary>
        internal static string HELMET {
            get {
                return ResourceManager.GetString("HELMET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schrank|Schränke.
        /// </summary>
        internal static string KITCHEN_CLOSETS {
            get {
                return ResourceManager.GetString("KITCHEN_CLOSETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAPTOP|Rechner|Computer.
        /// </summary>
        internal static string LAPTOP {
            get {
                return ResourceManager.GetString("LAPTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klinke|Türklinke|Türgriff.
        /// </summary>
        internal static string LATCH {
            get {
                return ResourceManager.GetString("LATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiegel.
        /// </summary>
        internal static string MIRROR {
            get {
                return ResourceManager.GetString("MIRROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notwendigkeiten|Notwendigkeit|nautische Notwendigkeiten|nautische Notwendigkeit.
        /// </summary>
        internal static string NECESSITIES {
            get {
                return ResourceManager.GetString("NECESSITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bürostuhl|Arbeitsstuhl|Sitzgelegenheit.
        /// </summary>
        internal static string OFFICECHAIR {
            get {
                return ResourceManager.GetString("OFFICECHAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umrisse|Umriss|Umriß.
        /// </summary>
        internal static string OUTLINES {
            get {
                return ResourceManager.GetString("OUTLINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ovoid.
        /// </summary>
        internal static string OVOID {
            get {
                return ResourceManager.GetString("OVOID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Sauerstoffflasche|Sauerstoffflasche|Sauerstoff-Flasche|Sauerstoff|Flasche.
        /// </summary>
        internal static string OXYGEN_BOTTLE {
            get {
                return ResourceManager.GetString("OXYGEN_BOTTLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trennwand|Sichtschutz.
        /// </summary>
        internal static string PARTITION_WALL {
            get {
                return ResourceManager.GetString("PARTITION_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guckloch.
        /// </summary>
        internal static string PEEPHOLE {
            get {
                return ResourceManager.GetString("PEEPHOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen|Einstellung|persönliche Einstellungen|persönliche Einstellung.
        /// </summary>
        internal static string PERSONAL_SETTINGS {
            get {
                return ResourceManager.GetString("PERSONAL_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullauge|Fenster|Weltraum|All|Weltall|Auge.
        /// </summary>
        internal static string PIERHOLE {
            get {
                return ResourceManager.GetString("PIERHOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Pilotensitz|Pilotensitz|Pilotsitz|Sitz|Pilotenstuhl|Stuhl.
        /// </summary>
        internal static string PILOT_SEAT {
            get {
                return ResourceManager.GetString("PILOT_SEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Gemälde|Gemälde|Portrait|Porträt|Bild|Bilder.
        /// </summary>
        internal static string PORTRAIT {
            get {
                return ResourceManager.GetString("PORTRAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rang|Rangs.
        /// </summary>
        internal static string RANK {
            get {
                return ResourceManager.GetString("RANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Reststoffverwerter|Reststoffverwerter|Verwerter|Recycler.
        /// </summary>
        internal static string RECYCLER {
            get {
                return ResourceManager.GetString("RECYCLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metallrollen|Rollen|Stuhlrollen|Gummi|Gummirollen.
        /// </summary>
        internal static string RUBBER_ROLLS {
            get {
                return ResourceManager.GetString("RUBBER_ROLLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Bio-Suit|Bio-Suit| Bio Suit|Space-Overall|Space Overall|Space-Suit|Space Suit|Overall|Anzug|Suit.
        /// </summary>
        internal static string SPACE_SUIT {
            get {
                return ResourceManager.GetString("SPACE_SUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Stepper|Stepper.
        /// </summary>
        internal static string STEPPER {
            get {
                return ResourceManager.GetString("STEPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Haftnotiz|Haftnotiz|Klebezettel|Notiz|Zettel.
        /// </summary>
        internal static string STICKY_NOTE {
            get {
                return ResourceManager.GetString("STICKY_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tisch.
        /// </summary>
        internal static string TABLE {
            get {
                return ResourceManager.GetString("TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toilette|Klo|Pott|Thron.
        /// </summary>
        internal static string TOILET {
            get {
                return ResourceManager.GetString("TOILET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toilettensitz|Klobrille|Klositz|WC-Sitz.
        /// </summary>
        internal static string TOILET_SEAT {
            get {
                return ResourceManager.GetString("TOILET_SEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Laufband|Laufband.
        /// </summary>
        internal static string TREADMILL {
            get {
                return ResourceManager.GetString("TREADMILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Garderobe|Garderobe.
        /// </summary>
        internal static string WARDROBE {
            get {
                return ResourceManager.GetString("WARDROBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waschmöglichkeit|Waschbereich|Bad|Badezimmer|Waschbecken.
        /// </summary>
        internal static string WASHINGAREA {
            get {
                return ResourceManager.GetString("WASHINGAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitsbereich|Arbeitsplatz|Schreibtisch.
        /// </summary>
        internal static string WORKBENCH {
            get {
                return ResourceManager.GetString("WORKBENCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übungen|Übung|Handarbeit.
        /// </summary>
        internal static string WORKOUTS {
            get {
                return ResourceManager.GetString("WORKOUTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Schreibutensilien|Schreibutensilien|Utensilien|Schreibmaterial|Schreibmaterialien|Papier|Blätter|Stifte|Stift|Textmarker.
        /// </summary>
        internal static string WRITING_MATERIALS {
            get {
                return ResourceManager.GetString("WRITING_MATERIALS", resourceCulture);
            }
        }
    }
}
