//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fenrir13.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Items {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Items() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fenrir13.Resources.Items", typeof(Items).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schott.
        /// </summary>
        internal static string AIRLOCK_BULKHEAD {
            get {
                return ResourceManager.GetString("AIRLOCK_BULKHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seilwinde|Seil|Winde.
        /// </summary>
        internal static string AIRLOCK_CABLE_WINCH {
            get {
                return ResourceManager.GetString("AIRLOCK_CABLE_WINCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tastenfeld|Tastatur.
        /// </summary>
        internal static string AIRLOCK_KEYPAD {
            get {
                return ResourceManager.GetString("AIRLOCK_KEYPAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grüne Knopf|Grüner Knopf|Grünen Knopf|Grüne Taste|CLOSE.
        /// </summary>
        internal static string AIRLOCK_KEYPAD_GREEN_BUTTON {
            get {
                return ResourceManager.GetString("AIRLOCK_KEYPAD_GREEN_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rote Knopf|Roter Knopf|Roten Knopf|Rote Taste|OPEN.
        /// </summary>
        internal static string AIRLOCK_KEYPAD_RED_BUTTON {
            get {
                return ResourceManager.GetString("AIRLOCK_KEYPAD_RED_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nördliche Wand.
        /// </summary>
        internal static string AIRLOCK_NORTHERN_WALL {
            get {
                return ResourceManager.GetString("AIRLOCK_NORTHERN_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphen-Seil|Seil|Sicherungsseil|Sicherungsleine|Leine.
        /// </summary>
        internal static string AIRLOCK_ROPE {
            get {
                return ResourceManager.GetString("AIRLOCK_ROPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Südliche Wand.
        /// </summary>
        internal static string AIRLOCK_SOUTHERN_WALL {
            get {
                return ResourceManager.GetString("AIRLOCK_SOUTHERN_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krankenbett|Krankenhausbett|Bett|Pflegebett.
        /// </summary>
        internal static string AMBULANCE_BED {
            get {
                return ResourceManager.GetString("AMBULANCE_BED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medikamente|Medis.
        /// </summary>
        internal static string AMBULANCE_MEDIS {
            get {
                return ResourceManager.GetString("AMBULANCE_MEDIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medizinschrank|Medischrank.
        /// </summary>
        internal static string AMBULANCE_MEDIS_CABINET {
            get {
                return ResourceManager.GetString("AMBULANCE_MEDIS_CABINET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OP-Schränke| OP Schränke|Schränke|Das Verbandszeug|Verbandszeug|Die Instrumente|Instrumente|Instrument|OP-Besteck.
        /// </summary>
        internal static string AMBULANCE_OP_ITEMS {
            get {
                return ResourceManager.GetString("AMBULANCE_OP_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinge|Skalpelle|Tupfer|Mullbinden|Adapter.
        /// </summary>
        internal static string AMBULANCE_OP_ITEMS_DETAIL {
            get {
                return ResourceManager.GetString("AMBULANCE_OP_ITEMS_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OP-Roboter| OP Roboter|Roboter|Arm|Arme|vier Arme.
        /// </summary>
        internal static string AMBULANCE_OP_ROBOTER {
            get {
                return ResourceManager.GetString("AMBULANCE_OP_ROBOTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OP-Tisch|OP Tisch|Tisch|Liegefläche|Tischplatte.
        /// </summary>
        internal static string AMBULANCE_OP_TABLE {
            get {
                return ResourceManager.GetString("AMBULANCE_OP_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schläuche.
        /// </summary>
        internal static string AMBULANCE_OXYGEN_HOSE {
            get {
                return ResourceManager.GetString("AMBULANCE_OXYGEN_HOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beatmungsgerät|Gerät|Oxygen|Korpus.
        /// </summary>
        internal static string AMBULANCE_RESPIRATOR {
            get {
                return ResourceManager.GetString("AMBULANCE_RESPIRATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verschlussklappe|Verschlusskappe|Klappe|Kappe.
        /// </summary>
        internal static string AMBULANCE_RESPIRATOR_FLAP {
            get {
                return ResourceManager.GetString("AMBULANCE_RESPIRATOR_FLAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sicherungsgurt|Gurt|Geschirr|Sicherungsgeschirr.
        /// </summary>
        internal static string BELT {
            get {
                return ResourceManager.GetString("BELT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fahrrad|Rad.
        /// </summary>
        internal static string BIKE {
            get {
                return ResourceManager.GetString("BIKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stiefel|Moonboots|Boots|Schuhe.
        /// </summary>
        internal static string BOOTS {
            get {
                return ResourceManager.GetString("BOOTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schott.
        /// </summary>
        internal static string BULKHEAD {
            get {
                return ResourceManager.GetString("BULKHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sichtfenster|Glas|Fenster.
        /// </summary>
        internal static string BULKHEAD_WINDOW {
            get {
                return ResourceManager.GetString("BULKHEAD_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardiostation|Cardiostationen|Cardio.
        /// </summary>
        internal static string CARDIO_STATION {
            get {
                return ResourceManager.GetString("CARDIO_STATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zimmerdecke|Decke.
        /// </summary>
        internal static string CEILING {
            get {
                return ResourceManager.GetString("CEILING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stuhl|Stühle.
        /// </summary>
        internal static string CHAIR {
            get {
                return ResourceManager.GetString("CHAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fußboden|Fussboden|Boden.
        /// </summary>
        internal static string CHAMBER_FLOOR {
            get {
                return ResourceManager.GetString("CHAMBER_FLOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wand|Zimmerwand|Wände|Zimmerwände|Raumwand|Raumwände.
        /// </summary>
        internal static string CHAMBER_WALL {
            get {
                return ResourceManager.GetString("CHAMBER_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power-Riegel|Powerriegel|Schokoladen-Riegel|Schokoladenriegel|Schoko-Riegel|Schokoriegel|Riegel.
        /// </summary>
        internal static string CHOCOLATEBAR {
            get {
                return ResourceManager.GetString("CHOCOLATEBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klettergerüst|Gerüst.
        /// </summary>
        internal static string CLIMBING_FRAME {
            get {
                return ResourceManager.GetString("CLIMBING_FRAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schrank|Kleiderschrank.
        /// </summary>
        internal static string CLOSET {
            get {
                return ResourceManager.GetString("CLOSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schranktür|Kleiderschranktür.
        /// </summary>
        internal static string CLOSET_DOOR {
            get {
                return ResourceManager.GetString("CLOSET_DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedienkonsole|Konsole|Platte|Glasplatte.
        /// </summary>
        internal static string CONTROL_PANEL {
            get {
                return ResourceManager.GetString("CONTROL_PANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrumente|Bilder|Informationstexte|Daten.
        /// </summary>
        internal static string CONTROL_PANEL_CONTENT {
            get {
                return ResourceManager.GetString("CONTROL_PANEL_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild|Bilder|Plakat|Poster.
        /// </summary>
        internal static string CORRIDOR_PAINTING {
            get {
                return ResourceManager.GetString("CORRIDOR_PAINTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wände|Wand.
        /// </summary>
        internal static string CORRIDOR_WALLS {
            get {
                return ResourceManager.GetString("CORRIDOR_WALLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullauge|Geöffnetes Bullauge.
        /// </summary>
        internal static string CORRIDOR_WEST_BULLEYE {
            get {
                return ResourceManager.GetString("CORRIDOR_WEST_BULLEYE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loch.
        /// </summary>
        internal static string CORRIDOR_WEST_HOLE {
            get {
                return ResourceManager.GetString("CORRIDOR_WEST_HOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schweißnaht.
        /// </summary>
        internal static string CORRIDOR_WEST_WELD_SEAM {
            get {
                return ResourceManager.GetString("CORRIDOR_WEST_WELD_SEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tür|Türen|Kammertür|Kammertüren|Crew-Kammern|Crew-Kammer|Crew Kammern|Crew Kammer|Kammern|Kammer|Crew-Kabinen|Crew-Kabine|Crewkabinen|Crewkabine|Kabinen|Kabine.
        /// </summary>
        internal static string CREW_DOORS {
            get {
                return ResourceManager.GetString("CREW_DOORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crewkammern|Crewkammer|Kammer|Kabinen|Kabine.
        /// </summary>
        internal static string CREWCHAMBERS {
            get {
                return ResourceManager.GetString("CREWCHAMBERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross-Trainer|Crosstrainer.
        /// </summary>
        internal static string CROSSTRAINER {
            get {
                return ResourceManager.GetString("CROSSTRAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sichtfenster|Glas.
        /// </summary>
        internal static string CRYOCHAMBER_BULKHEAD {
            get {
                return ResourceManager.GetString("CRYOCHAMBER_BULKHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klamotten|Kleidung|Strickjacke|Kleidungsstücke|Kleidungsstück.
        /// </summary>
        internal static string CRYOCHAMBER_CLOTHS {
            get {
                return ResourceManager.GetString("CRYOCHAMBER_CLOTHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zimmertür|Tür.
        /// </summary>
        internal static string CRYOCHAMBER_DOOR {
            get {
                return ResourceManager.GetString("CRYOCHAMBER_DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schreibtischlampe|Lampe|Glühbirne|Fassung|Teleskopstange|Teleskopstangen|Halterung|Beleuchtung.
        /// </summary>
        internal static string CRYOCHAMBER_LAMP {
            get {
                return ResourceManager.GetString("CRYOCHAMBER_LAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryopod|Cryo-Pod|Bett|Schlafplatz|Schlafkammer|Pod|Kokon.
        /// </summary>
        internal static string CRYOPOD {
            get {
                return ResourceManager.GetString("CRYOPOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display|Anzeige.
        /// </summary>
        internal static string DISPLAY {
            get {
                return ResourceManager.GetString("DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schublade|Schubladen|Schubfach|Schubfächer|Fächer.
        /// </summary>
        internal static string DRAWER {
            get {
                return ResourceManager.GetString("DRAWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service-Roboter|Serviceroboter|Wartungsroboter|Roboter|Droid.
        /// </summary>
        internal static string DROID {
            get {
                return ResourceManager.GetString("DROID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hantelstange|Stange|Hantel.
        /// </summary>
        internal static string DUMBBELL_BAR {
            get {
                return ResourceManager.GetString("DUMBBELL_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hantelablage|Ablage|Rack.
        /// </summary>
        internal static string DUMBBELL_RACK {
            get {
                return ResourceManager.GetString("DUMBBELL_RACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notbeleuchtung|Beleuchtung.
        /// </summary>
        internal static string EMERGENCY_LIGHT {
            get {
                return ResourceManager.GetString("EMERGENCY_LIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crew-Kammer-1|Crew-Kammer1|Kammer-1|Kammer1|Crew-Raum 1|Crew-Raum1|Raum-1|Raum1.
        /// </summary>
        internal static string EMPTYCREWCHAMBERONE {
            get {
                return ResourceManager.GetString("EMPTYCREWCHAMBERONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crew-Kammer-2|Crew-Kammer2|Kammer-2|Kammer2|Crew-Raum 2|Crew-Raum2|Raum-2|Raum2.
        /// </summary>
        internal static string EMPTYCREWCHAMBERTWO {
            get {
                return ResourceManager.GetString("EMPTYCREWCHAMBERTWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunst|Korona.
        /// </summary>
        internal static string ENGINE_ROOM_ART {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_ART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantencluster|Quantencomputer|Computer|Cluster.
        /// </summary>
        internal static string ENGINE_ROOM_COMPUTER {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_COMPUTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopfplatte|Platte|Kante.
        /// </summary>
        internal static string ENGINE_ROOM_HEAD {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_HEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rote Punkte|Punkte.
        /// </summary>
        internal static string ENGINE_ROOM_RED_DOTS {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_RED_DOTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hologramm|Hologram|Modell.
        /// </summary>
        internal static string ENGINE_ROOM_SHIP_MODEL {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_SHIP_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stelen|Stele|Säulen|Säule.
        /// </summary>
        internal static string ENGINE_ROOM_STEALING {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_STEALING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tangente.
        /// </summary>
        internal static string ENGINE_ROOM_TANGENT {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_TANGENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technik.
        /// </summary>
        internal static string ENGINE_ROOM_TECHNIC {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_TECHNIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metallkiste|Ausrüstungsbox|Ausrüstungsbox|Box|Kiste.
        /// </summary>
        internal static string EQUIPMENT_BOX {
            get {
                return ResourceManager.GetString("EQUIPMENT_BOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorhängeschloss|Schloss|Schloß.
        /// </summary>
        internal static string EQUIPMENT_BOX_LOCK {
            get {
                return ResourceManager.GetString("EQUIPMENT_BOX_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorhängeschloss|Schloss|Schloß.
        /// </summary>
        internal static string EQUIPMENT_BOX_LOCK_DESTROYED {
            get {
                return ResourceManager.GetString("EQUIPMENT_BOX_LOCK_DESTROYED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitzbänke|Sitzbank|Turnbänke|Turnbank|Bänke|Bank|Ausstattung.
        /// </summary>
        internal static string EQUIPMENT_ROOM_BENCH {
            get {
                return ResourceManager.GetString("EQUIPMENT_ROOM_BENCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kleidungsstücke|Kleidung.
        /// </summary>
        internal static string EQUIPMENT_ROOM_CLOTH {
            get {
                return ResourceManager.GetString("EQUIPMENT_ROOM_CLOTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nische|Wandnische|Nischen|Wandnischen.
        /// </summary>
        internal static string EQUIPMENT_ROOM_NICHE {
            get {
                return ResourceManager.GetString("EQUIPMENT_ROOM_NICHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mülleimer|Papiereimer|Papierkorb|Müllkorb|Abfalleimer|Abfallkorb|Korb|Eimer.
        /// </summary>
        internal static string EQUIPMENT_ROOM_TRASHBIN {
            get {
                return ResourceManager.GetString("EQUIPMENT_ROOM_TRASHBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gymnastikbereich.
        /// </summary>
        internal static string EXERCISE_AREA {
            get {
                return ResourceManager.GetString("EXERCISE_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öse.
        /// </summary>
        internal static string EYELET {
            get {
                return ResourceManager.GetString("EYELET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filzstoff|Filz.
        /// </summary>
        internal static string FELT {
            get {
                return ResourceManager.GetString("FELT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitnessmaschinen|Fitnessmaschine|Geräte|Plätze|Plätzen.
        /// </summary>
        internal static string FITNESSMACHINE {
            get {
                return ResourceManager.GetString("FITNESSMACHINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food-Printer|FoodPrinter|Foot Printer|Printer|Drucker.
        /// </summary>
        internal static string FOOD_PRINTER {
            get {
                return ResourceManager.GetString("FOOD_PRINTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kühlschrank.
        /// </summary>
        internal static string FRIDGE {
            get {
                return ResourceManager.GetString("FRIDGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türgriff|Griff.
        /// </summary>
        internal static string FRIDGE_DOOR_HANDLE {
            get {
                return ResourceManager.GetString("FRIDGE_DOOR_HANDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frontseite|Front.
        /// </summary>
        internal static string FRONTSIDE {
            get {
                return ResourceManager.GetString("FRONTSIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRONTWINDOW.
        /// </summary>
        internal static string FRONTWINDOW {
            get {
                return ResourceManager.GetString("FRONTWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handschuhe|Handschuh.
        /// </summary>
        internal static string GLOVES {
            get {
                return ResourceManager.GetString("GLOVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grüne Pfeile|Pfeile.
        /// </summary>
        internal static string GREEN_ARROWS {
            get {
                return ResourceManager.GetString("GREEN_ARROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halterung|Wand-Halterung|Wandhalterung.
        /// </summary>
        internal static string GYM_BRACKET {
            get {
                return ResourceManager.GetString("GYM_BRACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schlaufen|Griffe.
        /// </summary>
        internal static string GYM_LOOP {
            get {
                return ResourceManager.GetString("GYM_LOOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powerstation|Power|Gewichte.
        /// </summary>
        internal static string GYM_POWERSTATION {
            get {
                return ResourceManager.GetString("GYM_POWERSTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitness-Tau|Seil|Fitnesstau|Tau.
        /// </summary>
        internal static string GYM_ROPES {
            get {
                return ResourceManager.GetString("GYM_ROPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandsäcke|Säcke|Power Bags|Power-Bags.
        /// </summary>
        internal static string GYM_SANDBAG {
            get {
                return ResourceManager.GetString("GYM_SANDBAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weltraumhelm|Helm.
        /// </summary>
        internal static string HELMET {
            get {
                return ResourceManager.GetString("HELMET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loch.
        /// </summary>
        internal static string HOLE {
            get {
                return ResourceManager.GetString("HOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ionen-Strahlentriebwerke|Ionen Strahlentriebwerke|Strahlentriebwerke|Triebwerke.
        /// </summary>
        internal static string JETTY_ENGINE {
            get {
                return ResourceManager.GetString("JETTY_ENGINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hülle|Rückseite.
        /// </summary>
        internal static string JETTY_HULL {
            get {
                return ResourceManager.GetString("JETTY_HULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All|Sternenhimmel|Sterne|Himmel|Alpha Centauri.
        /// </summary>
        internal static string JETTY_SPACE {
            get {
                return ResourceManager.GetString("JETTY_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schrank|Schränke.
        /// </summary>
        internal static string KITCHEN_CABINET {
            get {
                return ResourceManager.GetString("KITCHEN_CABINET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beutelchen|Beutel|Kunststoff|Nahrungsbestandteile|Bestandteile.
        /// </summary>
        internal static string KITCHEN_FOOD_BAG {
            get {
                return ResourceManager.GetString("KITCHEN_FOOD_BAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAPTOP|Rechner|Computer.
        /// </summary>
        internal static string LAPTOP {
            get {
                return ResourceManager.GetString("LAPTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klinke|Türklinke|Türgriff.
        /// </summary>
        internal static string LATCH {
            get {
                return ResourceManager.GetString("LATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standort.
        /// </summary>
        internal static string LOCATION {
            get {
                return ResourceManager.GetString("LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schublade|Schubladen|Schubfach|Schubfächer|Fächer.
        /// </summary>
        internal static string MAINTENANCE_ROOM_DRAWER {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_DRAWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Griffe|Griff.
        /// </summary>
        internal static string MAINTENANCE_ROOM_DRAWER_HANDLE {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_DRAWER_HANDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Östliche Wand|Ost Wand.
        /// </summary>
        internal static string MAINTENANCE_ROOM_EAST_WALL {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_EAST_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platte|Arbeitsplatte.
        /// </summary>
        internal static string MAINTENANCE_ROOM_PLATE {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_PLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regal|Utensilien.
        /// </summary>
        internal static string MAINTENANCE_ROOM_SHELF {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_SHELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multifunktionswerkzeug|Werkzeug|Gerät.
        /// </summary>
        internal static string MAINTENANCE_ROOM_TOOL {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werkbank.
        /// </summary>
        internal static string MAINTENANCE_ROOM_WORKBENCH {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_WORKBENCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiegel.
        /// </summary>
        internal static string MIRROR {
            get {
                return ResourceManager.GetString("MIRROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notwendigkeiten|nautische Notwendigkeiten.
        /// </summary>
        internal static string NECESSITIES {
            get {
                return ResourceManager.GetString("NECESSITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bürostuhl|Arbeitsstuhl|Sitzgelegenheit.
        /// </summary>
        internal static string OFFICECHAIR {
            get {
                return ResourceManager.GetString("OFFICECHAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umrisse|Umriss|Umriß.
        /// </summary>
        internal static string OUTLINES {
            get {
                return ResourceManager.GetString("OUTLINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ovoid.
        /// </summary>
        internal static string OVOID {
            get {
                return ResourceManager.GetString("OVOID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauerstoffflasche|Sauerstoff-Flasche|Sauerstoff|Flasche|Gas.
        /// </summary>
        internal static string OXYGEN_BOTTLE {
            get {
                return ResourceManager.GetString("OXYGEN_BOTTLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lampen|Lampe|Kontrollleuchten|Kontrollleuchte.
        /// </summary>
        internal static string PANEL_TOP_LAMPS {
            get {
                return ResourceManager.GetString("PANEL_TOP_LAMPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handgriff|Hebel|Griff|Vorrichtung.
        /// </summary>
        internal static string PANEL_TOP_LEVER {
            get {
                return ResourceManager.GetString("PANEL_TOP_LEVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panele|Panels|Kollektoren.
        /// </summary>
        internal static string PANEL_TOP_PANELS {
            get {
                return ResourceManager.GetString("PANEL_TOP_PANELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metallummantelte Versorgungsleitung|Ummantelte Versorgungsleitung|Versorgungsleitung|Metallummantelte Leitung|Ummantelte Leitung|Leitung|Metallummantelte Versorgungsleitungen|Ummantelte Versorgungsleitungen|Versorgungsleitungen|Metallummantelte Leitungen|Ummantelte Leitungen|Leitungen.
        /// </summary>
        internal static string PANEL_TOP_SUPPLYLINES {
            get {
                return ResourceManager.GetString("PANEL_TOP_SUPPLYLINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fenster|Raumbeleuchtung|Beleuchtung.
        /// </summary>
        internal static string PANEL_TOP_WINDOWS {
            get {
                return ResourceManager.GetString("PANEL_TOP_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolfskopf|Wolf|Kopf|Steuerbordseite|Cargo-Bereich.
        /// </summary>
        internal static string PANEL_TOP_WOLF {
            get {
                return ResourceManager.GetString("PANEL_TOP_WOLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papier|Papierblätter|Blätter|Blatt|Papiere.
        /// </summary>
        internal static string PAPER {
            get {
                return ResourceManager.GetString("PAPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trennwand|Sichtschutz.
        /// </summary>
        internal static string PARTITION_WALL {
            get {
                return ResourceManager.GetString("PARTITION_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guckloch.
        /// </summary>
        internal static string PEEPHOLE {
            get {
                return ResourceManager.GetString("PEEPHOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kugelschreiber|Kuli.
        /// </summary>
        internal static string PENCIL_I {
            get {
                return ResourceManager.GetString("PENCIL_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bleistift.
        /// </summary>
        internal static string PENCIL_II {
            get {
                return ResourceManager.GetString("PENCIL_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stifte|Stift.
        /// </summary>
        internal static string PENCILS {
            get {
                return ResourceManager.GetString("PENCILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen|persönliche Einstellungen.
        /// </summary>
        internal static string PERSONAL_SETTINGS {
            get {
                return ResourceManager.GetString("PERSONAL_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullauge|Fenster|Weltraum|All|Weltall|Auge|Schiff|Raumschiff.
        /// </summary>
        internal static string PIERHOLE {
            get {
                return ResourceManager.GetString("PIERHOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilotensitz|Pilotsitz|Sitz|Pilotenstuhl|Stuhl.
        /// </summary>
        internal static string PILOT_SEAT {
            get {
                return ResourceManager.GetString("PILOT_SEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemälde|Portrait|Porträt|Bild|Bilder.
        /// </summary>
        internal static string PORTRAIT {
            get {
                return ResourceManager.GetString("PORTRAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxima Centauri|Roter Zwerg|Proxima|Centauri.
        /// </summary>
        internal static string PROXIMA_CENTAURI {
            get {
                return ResourceManager.GetString("PROXIMA_CENTAURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Würfel.
        /// </summary>
        internal static string QUATUM_CUBE {
            get {
                return ResourceManager.GetString("QUATUM_CUBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reststoffverwerter|Verwerter|Recycler.
        /// </summary>
        internal static string RECYCLER {
            get {
                return ResourceManager.GetString("RECYCLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roter Punkt|Punkt.
        /// </summary>
        internal static string RED_DOT {
            get {
                return ResourceManager.GetString("RED_DOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krallen|Kralle.
        /// </summary>
        internal static string ROOF_TOP_CLAW {
            get {
                return ResourceManager.GetString("ROOF_TOP_CLAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock|Ladedock.
        /// </summary>
        internal static string ROOF_TOP_DOCK {
            get {
                return ResourceManager.GetString("ROOF_TOP_DOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zimmertür|Tür.
        /// </summary>
        internal static string ROOM_DOOR {
            get {
                return ResourceManager.GetString("ROOM_DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halbrunde Treppe|Runde Treppe|Breite Treppe.
        /// </summary>
        internal static string ROUND_STAIRS {
            get {
                return ResourceManager.GetString("ROUND_STAIRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boardwand.
        /// </summary>
        internal static string SIDEWALL {
            get {
                return ResourceManager.GetString("SIDEWALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebrauchsspuren|Spuren|Schnitte|Macken|Kerben|Gebrauchsspur|Spur|Macke|Kerbe.
        /// </summary>
        internal static string SIGNS_OF_USE {
            get {
                return ResourceManager.GetString("SIGNS_OF_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antenne.
        /// </summary>
        internal static string SOCIALROOM_ANTENNA {
            get {
                return ResourceManager.GetString("SOCIALROOM_ANTENNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver|Antennenkonstruktion|Konstruktion|Funknetz.
        /// </summary>
        internal static string SOCIALROOM_ANTENNA_CONSTRUCTION {
            get {
                return ResourceManager.GetString("SOCIALROOM_ANTENNA_CONSTRUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billardtisch.
        /// </summary>
        internal static string SOCIALROOM_BILLARD {
            get {
                return ResourceManager.GetString("SOCIALROOM_BILLARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kugeln|Kugel.
        /// </summary>
        internal static string SOCIALROOM_BILLARD_BALLS {
            get {
                return ResourceManager.GetString("SOCIALROOM_BILLARD_BALLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bürste.
        /// </summary>
        internal static string SOCIALROOM_BILLARD_BRUSH {
            get {
                return ResourceManager.GetString("SOCIALROOM_BILLARD_BRUSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreide.
        /// </summary>
        internal static string SOCIALROOM_BILLARD_CHALK {
            get {
                return ResourceManager.GetString("SOCIALROOM_BILLARD_CHALK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cue|Queue|Cues.
        /// </summary>
        internal static string SOCIALROOM_BILLARD_CUE {
            get {
                return ResourceManager.GetString("SOCIALROOM_BILLARD_CUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wandhalterung.
        /// </summary>
        internal static string SOCIALROOM_BILLARD_THINGS {
            get {
                return ResourceManager.GetString("SOCIALROOM_BILLARD_THINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dreieck.
        /// </summary>
        internal static string SOCIALROOM_BILLARD_TRIANGLE {
            get {
                return ResourceManager.GetString("SOCIALROOM_BILLARD_TRIANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bücher|Buch|Bücherregal|Regal.
        /// </summary>
        internal static string SOCIALROOM_BOOKS {
            get {
                return ResourceManager.GetString("SOCIALROOM_BOOKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decke|Zimmer Decke.
        /// </summary>
        internal static string SOCIALROOM_CEILING {
            get {
                return ResourceManager.GetString("SOCIALROOM_CEILING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couch|Sofa.
        /// </summary>
        internal static string SOCIALROOM_COUCH {
            get {
                return ResourceManager.GetString("SOCIALROOM_COUCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dartscheibe|Darts|Dart|Pfeile|Pfeil.
        /// </summary>
        internal static string SOCIALROOM_DARTS {
            get {
                return ResourceManager.GetString("SOCIALROOM_DARTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Östliche Wand|Ost Wand.
        /// </summary>
        internal static string SOCIALROOM_EAST_WALL {
            get {
                return ResourceManager.GetString("SOCIALROOM_EAST_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glastisch|Tisch.
        /// </summary>
        internal static string SOCIALROOM_GLASS_TABLE {
            get {
                return ResourceManager.GetString("SOCIALROOM_GLASS_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediaserver.
        /// </summary>
        internal static string SOCIALROOM_MEDIASERVER {
            get {
                return ResourceManager.GetString("SOCIALROOM_MEDIASERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildschirm|Fernseher.
        /// </summary>
        internal static string SOCIALROOM_MONITOR {
            get {
                return ResourceManager.GetString("SOCIALROOM_MONITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nördliche Wand| Nord Wand.
        /// </summary>
        internal static string SOCIALROOM_NORTH_WALL {
            get {
                return ResourceManager.GetString("SOCIALROOM_NORTH_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessel|Sitz.
        /// </summary>
        internal static string SOCIALROOM_SEAT {
            get {
                return ResourceManager.GetString("SOCIALROOM_SEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitzgruppe.
        /// </summary>
        internal static string SOCIALROOM_SEATGROUP {
            get {
                return ResourceManager.GetString("SOCIALROOM_SEATGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Südliche Wand|Süd Wand.
        /// </summary>
        internal static string SOCIALROOM_SOUTH_WALL {
            get {
                return ResourceManager.GetString("SOCIALROOM_SOUTH_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wand.
        /// </summary>
        internal static string SOCIALROOM_WALL {
            get {
                return ResourceManager.GetString("SOCIALROOM_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Westliche Wand|West Wand.
        /// </summary>
        internal static string SOCIALROOM_WEST_WALL {
            get {
                return ResourceManager.GetString("SOCIALROOM_WEST_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leiter|Sprossen|Sprosse|Schienen|Schiene.
        /// </summary>
        internal static string SPACE_LADDER {
            get {
                return ResourceManager.GetString("SPACE_LADDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio-Suit| Bio Suit|Space-Overall|Space Overall|Space-Suit|Space Suit|Overall|Anzug|Suit.
        /// </summary>
        internal static string SPACE_SUIT {
            get {
                return ResourceManager.GetString("SPACE_SUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treppe.
        /// </summary>
        internal static string STAIRS {
            get {
                return ResourceManager.GetString("STAIRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepper.
        /// </summary>
        internal static string STEPPER {
            get {
                return ResourceManager.GetString("STEPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haftnotiz|Klebezettel|Notiz|Zettel.
        /// </summary>
        internal static string STICKY_NOTE {
            get {
                return ResourceManager.GetString("STICKY_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tisch|Metallrahmen|Kunststofftischplatte.
        /// </summary>
        internal static string TABLE {
            get {
                return ResourceManager.GetString("TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toilette|Klo|Pott|Thron.
        /// </summary>
        internal static string TOILET {
            get {
                return ResourceManager.GetString("TOILET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toilettensitz|Klobrille|Klositz|WC-Sitz.
        /// </summary>
        internal static string TOILET_SEAT {
            get {
                return ResourceManager.GetString("TOILET_SEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laufband.
        /// </summary>
        internal static string TREADMILL {
            get {
                return ResourceManager.GetString("TREADMILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garderobe.
        /// </summary>
        internal static string WARDROBE {
            get {
                return ResourceManager.GetString("WARDROBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waschmöglichkeit|Waschbereich|Bad|Badezimmer|Waschbecken.
        /// </summary>
        internal static string WASHINGAREA {
            get {
                return ResourceManager.GetString("WASHINGAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hantelscheiben|Hantelscheibe|Hantel.
        /// </summary>
        internal static string WEIGHT_PLATES {
            get {
                return ResourceManager.GetString("WEIGHT_PLATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitsbereich|Arbeitsplatz|Schreibtisch|Arbeitsplatte|Platte.
        /// </summary>
        internal static string WORKBENCH {
            get {
                return ResourceManager.GetString("WORKBENCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übungen|Übung|Ertüchtigung.
        /// </summary>
        internal static string WORKOUTS {
            get {
                return ResourceManager.GetString("WORKOUTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schreibutensilien|Utensilien|Schreibmaterial|Schreibmaterialien|Ablagefächer|Ablagefach.
        /// </summary>
        internal static string WRITING_MATERIALS {
            get {
                return ResourceManager.GetString("WRITING_MATERIALS", resourceCulture);
            }
        }
    }
}
