//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fenrir13.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Keys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Keys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fenrir13.Resources.Keys", typeof(Keys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIRLOCK.
        /// </summary>
        internal static string AIRLOCK {
            get {
                return ResourceManager.GetString("AIRLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIRLOCK_BULKHEAD.
        /// </summary>
        internal static string AIRLOCK_BULKHEAD {
            get {
                return ResourceManager.GetString("AIRLOCK_BULKHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIRLOCK_CABLE_WINCH.
        /// </summary>
        internal static string AIRLOCK_CABLE_WINCH {
            get {
                return ResourceManager.GetString("AIRLOCK_CABLE_WINCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIRLOCK_KEYPAD.
        /// </summary>
        internal static string AIRLOCK_KEYPAD {
            get {
                return ResourceManager.GetString("AIRLOCK_KEYPAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIRLOCK_KEYPAD_GREEN_BUTTON.
        /// </summary>
        internal static string AIRLOCK_KEYPAD_GREEN_BUTTON {
            get {
                return ResourceManager.GetString("AIRLOCK_KEYPAD_GREEN_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIRLOCK_KEYPAD_RED_BUTTON.
        /// </summary>
        internal static string AIRLOCK_KEYPAD_RED_BUTTON {
            get {
                return ResourceManager.GetString("AIRLOCK_KEYPAD_RED_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIRLOCK_NORTHERN_WALL.
        /// </summary>
        internal static string AIRLOCK_NORTHERN_WALL {
            get {
                return ResourceManager.GetString("AIRLOCK_NORTHERN_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIRLOCK_ROPE.
        /// </summary>
        internal static string AIRLOCK_ROPE {
            get {
                return ResourceManager.GetString("AIRLOCK_ROPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIRLOCK_SOUTHERN_WALL.
        /// </summary>
        internal static string AIRLOCK_SOUTHERN_WALL {
            get {
                return ResourceManager.GetString("AIRLOCK_SOUTHERN_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMBULANCE.
        /// </summary>
        internal static string AMBULANCE {
            get {
                return ResourceManager.GetString("AMBULANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMBULANCE_BED.
        /// </summary>
        internal static string AMBULANCE_BED {
            get {
                return ResourceManager.GetString("AMBULANCE_BED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMBULANCE_MEDIS.
        /// </summary>
        internal static string AMBULANCE_MEDIS {
            get {
                return ResourceManager.GetString("AMBULANCE_MEDIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMBULANCE_MEDIS_CABINET.
        /// </summary>
        internal static string AMBULANCE_MEDIS_CABINET {
            get {
                return ResourceManager.GetString("AMBULANCE_MEDIS_CABINET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMBULANCE_OP_ITEMS.
        /// </summary>
        internal static string AMBULANCE_OP_ITEMS {
            get {
                return ResourceManager.GetString("AMBULANCE_OP_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMBULANCE_OP_ITEMS_DETAIL.
        /// </summary>
        internal static string AMBULANCE_OP_ITEMS_DETAIL {
            get {
                return ResourceManager.GetString("AMBULANCE_OP_ITEMS_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMBULANCE_OP_ROBOTER.
        /// </summary>
        internal static string AMBULANCE_OP_ROBOTER {
            get {
                return ResourceManager.GetString("AMBULANCE_OP_ROBOTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMBULANCE_OP_TABLE.
        /// </summary>
        internal static string AMBULANCE_OP_TABLE {
            get {
                return ResourceManager.GetString("AMBULANCE_OP_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMBULANCE_OXYGEN_HOSE.
        /// </summary>
        internal static string AMBULANCE_OXYGEN_HOSE {
            get {
                return ResourceManager.GetString("AMBULANCE_OXYGEN_HOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMBULANCE_RESPIRATOR.
        /// </summary>
        internal static string AMBULANCE_RESPIRATOR {
            get {
                return ResourceManager.GetString("AMBULANCE_RESPIRATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMBULANCE_RESPIRATOR_FLAP.
        /// </summary>
        internal static string AMBULANCE_RESPIRATOR_FLAP {
            get {
                return ResourceManager.GetString("AMBULANCE_RESPIRATOR_FLAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BELT.
        /// </summary>
        internal static string BELT {
            get {
                return ResourceManager.GetString("BELT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIKE.
        /// </summary>
        internal static string BIKE {
            get {
                return ResourceManager.GetString("BIKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOTS.
        /// </summary>
        internal static string BOOTS {
            get {
                return ResourceManager.GetString("BOOTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BULKHEAD.
        /// </summary>
        internal static string BULKHEAD {
            get {
                return ResourceManager.GetString("BULKHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BULKHEAD_WINDOW.
        /// </summary>
        internal static string BULKHEAD_WINDOW {
            get {
                return ResourceManager.GetString("BULKHEAD_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARDIO_STATION.
        /// </summary>
        internal static string CARDIO_STATION {
            get {
                return ResourceManager.GetString("CARDIO_STATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEILING.
        /// </summary>
        internal static string CEILING {
            get {
                return ResourceManager.GetString("CEILING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAIR.
        /// </summary>
        internal static string CHAIR {
            get {
                return ResourceManager.GetString("CHAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAMBER_FLOOR.
        /// </summary>
        internal static string CHAMBER_FLOOR {
            get {
                return ResourceManager.GetString("CHAMBER_FLOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAMBER_WALL.
        /// </summary>
        internal static string CHAMBER_WALL {
            get {
                return ResourceManager.GetString("CHAMBER_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOCOLATEBAR.
        /// </summary>
        internal static string CHOCOLATEBAR {
            get {
                return ResourceManager.GetString("CHOCOLATEBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLIMBING_FRAME.
        /// </summary>
        internal static string CLIMBING_FRAME {
            get {
                return ResourceManager.GetString("CLIMBING_FRAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSET.
        /// </summary>
        internal static string CLOSET {
            get {
                return ResourceManager.GetString("CLOSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSET_DOOR.
        /// </summary>
        internal static string CLOSET_DOOR {
            get {
                return ResourceManager.GetString("CLOSET_DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMANDBRIDGE.
        /// </summary>
        internal static string COMMANDBRIDGE {
            get {
                return ResourceManager.GetString("COMMANDBRIDGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPUTER_TERMINAL.
        /// </summary>
        internal static string COMPUTER_TERMINAL {
            get {
                return ResourceManager.GetString("COMPUTER_TERMINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTROL_PANEL.
        /// </summary>
        internal static string CONTROL_PANEL {
            get {
                return ResourceManager.GetString("CONTROL_PANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTROL_PANEL_CONTENT.
        /// </summary>
        internal static string CONTROL_PANEL_CONTENT {
            get {
                return ResourceManager.GetString("CONTROL_PANEL_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORRIDOR_EAST.
        /// </summary>
        internal static string CORRIDOR_EAST {
            get {
                return ResourceManager.GetString("CORRIDOR_EAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORRIDOR_MID.
        /// </summary>
        internal static string CORRIDOR_MID {
            get {
                return ResourceManager.GetString("CORRIDOR_MID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORRIDOR_MIDEAST.
        /// </summary>
        internal static string CORRIDOR_MIDEAST {
            get {
                return ResourceManager.GetString("CORRIDOR_MIDEAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORRIDOR_MIDWEST.
        /// </summary>
        internal static string CORRIDOR_MIDWEST {
            get {
                return ResourceManager.GetString("CORRIDOR_MIDWEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORRIDOR_PAINTING.
        /// </summary>
        internal static string CORRIDOR_PAINTING {
            get {
                return ResourceManager.GetString("CORRIDOR_PAINTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORRIDOR_WALLS.
        /// </summary>
        internal static string CORRIDOR_WALLS {
            get {
                return ResourceManager.GetString("CORRIDOR_WALLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORRIDOR_WEST.
        /// </summary>
        internal static string CORRIDOR_WEST {
            get {
                return ResourceManager.GetString("CORRIDOR_WEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORRIDOR_WEST_BULLEYE.
        /// </summary>
        internal static string CORRIDOR_WEST_BULLEYE {
            get {
                return ResourceManager.GetString("CORRIDOR_WEST_BULLEYE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORRIDOR_WEST_HOLE.
        /// </summary>
        internal static string CORRIDOR_WEST_HOLE {
            get {
                return ResourceManager.GetString("CORRIDOR_WEST_HOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORRIDOR_WEST_WELD_SEAM.
        /// </summary>
        internal static string CORRIDOR_WEST_WELD_SEAM {
            get {
                return ResourceManager.GetString("CORRIDOR_WEST_WELD_SEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREW_DOORS.
        /// </summary>
        internal static string CREW_DOORS {
            get {
                return ResourceManager.GetString("CREW_DOORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREWCHAMBERS.
        /// </summary>
        internal static string CREWCHAMBERS {
            get {
                return ResourceManager.GetString("CREWCHAMBERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CROSSTRAINER.
        /// </summary>
        internal static string CROSSTRAINER {
            get {
                return ResourceManager.GetString("CROSSTRAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRYOCHAMBER.
        /// </summary>
        internal static string CRYOCHAMBER {
            get {
                return ResourceManager.GetString("CRYOCHAMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRYOCHAMBER_BULKHEAD.
        /// </summary>
        internal static string CRYOCHAMBER_BULKHEAD {
            get {
                return ResourceManager.GetString("CRYOCHAMBER_BULKHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRYOCHAMBER_CLOTHS.
        /// </summary>
        internal static string CRYOCHAMBER_CLOTHS {
            get {
                return ResourceManager.GetString("CRYOCHAMBER_CLOTHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRYOCHAMBER_DOOR.
        /// </summary>
        internal static string CRYOCHAMBER_DOOR {
            get {
                return ResourceManager.GetString("CRYOCHAMBER_DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRYOCHAMBER_LAMP.
        /// </summary>
        internal static string CRYOCHAMBER_LAMP {
            get {
                return ResourceManager.GetString("CRYOCHAMBER_LAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRYOPOD.
        /// </summary>
        internal static string CRYOPOD {
            get {
                return ResourceManager.GetString("CRYOPOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISPLAY.
        /// </summary>
        internal static string DISPLAY {
            get {
                return ResourceManager.GetString("DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRAWER.
        /// </summary>
        internal static string DRAWER {
            get {
                return ResourceManager.GetString("DRAWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROID.
        /// </summary>
        internal static string DROID {
            get {
                return ResourceManager.GetString("DROID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUMBBELL_BAR.
        /// </summary>
        internal static string DUMBBELL_BAR {
            get {
                return ResourceManager.GetString("DUMBBELL_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUMBBELL_RACK.
        /// </summary>
        internal static string DUMBBELL_RACK {
            get {
                return ResourceManager.GetString("DUMBBELL_RACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMERGENCY_LIGHT.
        /// </summary>
        internal static string EMERGENCY_LIGHT {
            get {
                return ResourceManager.GetString("EMERGENCY_LIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMPTYCREWCHAMBERONE.
        /// </summary>
        internal static string EMPTYCREWCHAMBERONE {
            get {
                return ResourceManager.GetString("EMPTYCREWCHAMBERONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMPTYCREWCHAMBERTWO.
        /// </summary>
        internal static string EMPTYCREWCHAMBERTWO {
            get {
                return ResourceManager.GetString("EMPTYCREWCHAMBERTWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENGINE_ROOM.
        /// </summary>
        internal static string ENGINE_ROOM {
            get {
                return ResourceManager.GetString("ENGINE_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENGINE_ROOM_ART.
        /// </summary>
        internal static string ENGINE_ROOM_ART {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_ART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENGINE_ROOM_COMPUTER.
        /// </summary>
        internal static string ENGINE_ROOM_COMPUTER {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_COMPUTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENGINE_ROOM_HEAD.
        /// </summary>
        internal static string ENGINE_ROOM_HEAD {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_HEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENGINE_ROOM_RED_DOTS.
        /// </summary>
        internal static string ENGINE_ROOM_RED_DOTS {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_RED_DOTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENGINE_ROOM_SHIP_MODEL.
        /// </summary>
        internal static string ENGINE_ROOM_SHIP_MODEL {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_SHIP_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENGINE_ROOM_STEALING.
        /// </summary>
        internal static string ENGINE_ROOM_STEALING {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_STEALING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENGINE_ROOM_TANGENT.
        /// </summary>
        internal static string ENGINE_ROOM_TANGENT {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_TANGENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENGINE_ROOM_TECHNIC.
        /// </summary>
        internal static string ENGINE_ROOM_TECHNIC {
            get {
                return ResourceManager.GetString("ENGINE_ROOM_TECHNIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQUIPMENT_BOX.
        /// </summary>
        internal static string EQUIPMENT_BOX {
            get {
                return ResourceManager.GetString("EQUIPMENT_BOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQUIPMENT_BOX_LOCK.
        /// </summary>
        internal static string EQUIPMENT_BOX_LOCK {
            get {
                return ResourceManager.GetString("EQUIPMENT_BOX_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das zerstörte und unbrauchbare Schloss liegt auf dem Boden..
        /// </summary>
        internal static string EQUIPMENT_BOX_LOCK_BREAK_CONTAINMENT {
            get {
                return ResourceManager.GetString("EQUIPMENT_BOX_LOCK_BREAK_CONTAINMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQUIPMENT_BOX_LOCK_DESTROYED.
        /// </summary>
        internal static string EQUIPMENT_BOX_LOCK_DESTROYED {
            get {
                return ResourceManager.GetString("EQUIPMENT_BOX_LOCK_DESTROYED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQUIPMENT_ROOM.
        /// </summary>
        internal static string EQUIPMENT_ROOM {
            get {
                return ResourceManager.GetString("EQUIPMENT_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQUIPMENT_ROOM_BENCH.
        /// </summary>
        internal static string EQUIPMENT_ROOM_BENCH {
            get {
                return ResourceManager.GetString("EQUIPMENT_ROOM_BENCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQUIPMENT_ROOM_CLOTH.
        /// </summary>
        internal static string EQUIPMENT_ROOM_CLOTH {
            get {
                return ResourceManager.GetString("EQUIPMENT_ROOM_CLOTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQUIPMENT_ROOM_NICHE.
        /// </summary>
        internal static string EQUIPMENT_ROOM_NICHE {
            get {
                return ResourceManager.GetString("EQUIPMENT_ROOM_NICHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQUIPMENT_ROOM_TRASHBIN.
        /// </summary>
        internal static string EQUIPMENT_ROOM_TRASHBIN {
            get {
                return ResourceManager.GetString("EQUIPMENT_ROOM_TRASHBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXERCISE_AREA.
        /// </summary>
        internal static string EXERCISE_AREA {
            get {
                return ResourceManager.GetString("EXERCISE_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EYELET.
        /// </summary>
        internal static string EYELET {
            get {
                return ResourceManager.GetString("EYELET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FELT.
        /// </summary>
        internal static string FELT {
            get {
                return ResourceManager.GetString("FELT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FITNESSMACHINE.
        /// </summary>
        internal static string FITNESSMACHINE {
            get {
                return ResourceManager.GetString("FITNESSMACHINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOOD_PRINTER.
        /// </summary>
        internal static string FOOD_PRINTER {
            get {
                return ResourceManager.GetString("FOOD_PRINTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRIDGE.
        /// </summary>
        internal static string FRIDGE {
            get {
                return ResourceManager.GetString("FRIDGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRIDGE_DOOR_HANDLE.
        /// </summary>
        internal static string FRIDGE_DOOR_HANDLE {
            get {
                return ResourceManager.GetString("FRIDGE_DOOR_HANDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRONTSIDE.
        /// </summary>
        internal static string FRONTSIDE {
            get {
                return ResourceManager.GetString("FRONTSIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRONTWINDOW.
        /// </summary>
        internal static string FRONTWINDOW {
            get {
                return ResourceManager.GetString("FRONTWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLOVES.
        /// </summary>
        internal static string GLOVES {
            get {
                return ResourceManager.GetString("GLOVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GREEN_ARROWS.
        /// </summary>
        internal static string GREEN_ARROWS {
            get {
                return ResourceManager.GetString("GREEN_ARROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GYM.
        /// </summary>
        internal static string GYM {
            get {
                return ResourceManager.GetString("GYM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GYM_BRACKET.
        /// </summary>
        internal static string GYM_BRACKET {
            get {
                return ResourceManager.GetString("GYM_BRACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GYM_LOOP.
        /// </summary>
        internal static string GYM_LOOP {
            get {
                return ResourceManager.GetString("GYM_LOOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GYM_POWERSTATION.
        /// </summary>
        internal static string GYM_POWERSTATION {
            get {
                return ResourceManager.GetString("GYM_POWERSTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GYM_ROPES.
        /// </summary>
        internal static string GYM_ROPES {
            get {
                return ResourceManager.GetString("GYM_ROPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GYM_SANDBAG.
        /// </summary>
        internal static string GYM_SANDBAG {
            get {
                return ResourceManager.GetString("GYM_SANDBAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELMET.
        /// </summary>
        internal static string HELMET {
            get {
                return ResourceManager.GetString("HELMET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOLE.
        /// </summary>
        internal static string HOLE {
            get {
                return ResourceManager.GetString("HOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JETTY.
        /// </summary>
        internal static string JETTY {
            get {
                return ResourceManager.GetString("JETTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JETTY_ALPHA.
        /// </summary>
        internal static string JETTY_ALPHA {
            get {
                return ResourceManager.GetString("JETTY_ALPHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JETTY_ENGINE.
        /// </summary>
        internal static string JETTY_ENGINE {
            get {
                return ResourceManager.GetString("JETTY_ENGINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JETTY_HULL.
        /// </summary>
        internal static string JETTY_HULL {
            get {
                return ResourceManager.GetString("JETTY_HULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JETTY_SPACE.
        /// </summary>
        internal static string JETTY_SPACE {
            get {
                return ResourceManager.GetString("JETTY_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KITCHEN.
        /// </summary>
        internal static string KITCHEN {
            get {
                return ResourceManager.GetString("KITCHEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KITCHEN_CABINET.
        /// </summary>
        internal static string KITCHEN_CABINET {
            get {
                return ResourceManager.GetString("KITCHEN_CABINET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KITCHEN_FOOD_BAG.
        /// </summary>
        internal static string KITCHEN_FOOD_BAG {
            get {
                return ResourceManager.GetString("KITCHEN_FOOD_BAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAPTOP.
        /// </summary>
        internal static string LAPTOP {
            get {
                return ResourceManager.GetString("LAPTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LATCH.
        /// </summary>
        internal static string LATCH {
            get {
                return ResourceManager.GetString("LATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCATION.
        /// </summary>
        internal static string LOCATION {
            get {
                return ResourceManager.GetString("LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MACHINE_CORRIDOR_MID.
        /// </summary>
        internal static string MACHINE_CORRIDOR_MID {
            get {
                return ResourceManager.GetString("MACHINE_CORRIDOR_MID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAINTENANCE_ROOM.
        /// </summary>
        internal static string MAINTENANCE_ROOM {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAINTENANCE_ROOM_DRAWER.
        /// </summary>
        internal static string MAINTENANCE_ROOM_DRAWER {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_DRAWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAINTENANCE_ROOM_DRAWER_HANDLE.
        /// </summary>
        internal static string MAINTENANCE_ROOM_DRAWER_HANDLE {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_DRAWER_HANDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAINTENANCE_ROOM_EAST_WALL.
        /// </summary>
        internal static string MAINTENANCE_ROOM_EAST_WALL {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_EAST_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAINTENANCE_ROOM_PLATE.
        /// </summary>
        internal static string MAINTENANCE_ROOM_PLATE {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_PLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAINTENANCE_ROOM_SHELF.
        /// </summary>
        internal static string MAINTENANCE_ROOM_SHELF {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_SHELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAINTENANCE_ROOM_TOOL.
        /// </summary>
        internal static string MAINTENANCE_ROOM_TOOL {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAINTENANCE_ROOM_UTILS.
        /// </summary>
        internal static string MAINTENANCE_ROOM_UTILS {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_UTILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAINTENANCE_ROOM_WORKBENCH.
        /// </summary>
        internal static string MAINTENANCE_ROOM_WORKBENCH {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM_WORKBENCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIRROR.
        /// </summary>
        internal static string MIRROR {
            get {
                return ResourceManager.GetString("MIRROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NECESSITIES.
        /// </summary>
        internal static string NECESSITIES {
            get {
                return ResourceManager.GetString("NECESSITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFFICECHAIR.
        /// </summary>
        internal static string OFFICECHAIR {
            get {
                return ResourceManager.GetString("OFFICECHAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTLINES.
        /// </summary>
        internal static string OUTLINES {
            get {
                return ResourceManager.GetString("OUTLINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVOID.
        /// </summary>
        internal static string OVOID {
            get {
                return ResourceManager.GetString("OVOID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OXYGEN_BOTTLE.
        /// </summary>
        internal static string OXYGEN_BOTTLE {
            get {
                return ResourceManager.GetString("OXYGEN_BOTTLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PANEL_TOP.
        /// </summary>
        internal static string PANEL_TOP {
            get {
                return ResourceManager.GetString("PANEL_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PANEL_TOP_LAMPS.
        /// </summary>
        internal static string PANEL_TOP_LAMPS {
            get {
                return ResourceManager.GetString("PANEL_TOP_LAMPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PANEL_TOP_LEVER.
        /// </summary>
        internal static string PANEL_TOP_LEVER {
            get {
                return ResourceManager.GetString("PANEL_TOP_LEVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PANEL_TOP_PANELS.
        /// </summary>
        internal static string PANEL_TOP_PANELS {
            get {
                return ResourceManager.GetString("PANEL_TOP_PANELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PANEL_TOP_SUPPLYLINES.
        /// </summary>
        internal static string PANEL_TOP_SUPPLYLINES {
            get {
                return ResourceManager.GetString("PANEL_TOP_SUPPLYLINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PANEL_TOP_WINDOWS.
        /// </summary>
        internal static string PANEL_TOP_WINDOWS {
            get {
                return ResourceManager.GetString("PANEL_TOP_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PANEL_TOP_WOLF.
        /// </summary>
        internal static string PANEL_TOP_WOLF {
            get {
                return ResourceManager.GetString("PANEL_TOP_WOLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAPER.
        /// </summary>
        internal static string PAPER {
            get {
                return ResourceManager.GetString("PAPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARTITION_WALL.
        /// </summary>
        internal static string PARTITION_WALL {
            get {
                return ResourceManager.GetString("PARTITION_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEEPHOLE.
        /// </summary>
        internal static string PEEPHOLE {
            get {
                return ResourceManager.GetString("PEEPHOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PENCIL_I.
        /// </summary>
        internal static string PENCIL_I {
            get {
                return ResourceManager.GetString("PENCIL_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PENCIL_II.
        /// </summary>
        internal static string PENCIL_II {
            get {
                return ResourceManager.GetString("PENCIL_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PENCILS.
        /// </summary>
        internal static string PENCILS {
            get {
                return ResourceManager.GetString("PENCILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERSONAL_SETTINGS.
        /// </summary>
        internal static string PERSONAL_SETTINGS {
            get {
                return ResourceManager.GetString("PERSONAL_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIERHOLE.
        /// </summary>
        internal static string PIERHOLE {
            get {
                return ResourceManager.GetString("PIERHOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PILOT_SEAT.
        /// </summary>
        internal static string PILOT_SEAT {
            get {
                return ResourceManager.GetString("PILOT_SEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYER.
        /// </summary>
        internal static string PLAYER {
            get {
                return ResourceManager.GetString("PLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTRAIT.
        /// </summary>
        internal static string PORTRAIT {
            get {
                return ResourceManager.GetString("PORTRAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROXIMA_CENTAURI.
        /// </summary>
        internal static string PROXIMA_CENTAURI {
            get {
                return ResourceManager.GetString("PROXIMA_CENTAURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUATUM_CUBE.
        /// </summary>
        internal static string QUATUM_CUBE {
            get {
                return ResourceManager.GetString("QUATUM_CUBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECYCLER.
        /// </summary>
        internal static string RECYCLER {
            get {
                return ResourceManager.GetString("RECYCLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RED_DOT.
        /// </summary>
        internal static string RED_DOT {
            get {
                return ResourceManager.GetString("RED_DOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROOF_TOP.
        /// </summary>
        internal static string ROOF_TOP {
            get {
                return ResourceManager.GetString("ROOF_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROOF_TOP_CLAW.
        /// </summary>
        internal static string ROOF_TOP_CLAW {
            get {
                return ResourceManager.GetString("ROOF_TOP_CLAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROOF_TOP_DOCK.
        /// </summary>
        internal static string ROOF_TOP_DOCK {
            get {
                return ResourceManager.GetString("ROOF_TOP_DOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROOM_DOOR.
        /// </summary>
        internal static string ROOM_DOOR {
            get {
                return ResourceManager.GetString("ROOM_DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROUND_STAIRS.
        /// </summary>
        internal static string ROUND_STAIRS {
            get {
                return ResourceManager.GetString("ROUND_STAIRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIDEWALL.
        /// </summary>
        internal static string SIDEWALL {
            get {
                return ResourceManager.GetString("SIDEWALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGNS_OF_USE.
        /// </summary>
        internal static string SIGNS_OF_USE {
            get {
                return ResourceManager.GetString("SIGNS_OF_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIALROOM.
        /// </summary>
        internal static string SOCIALROOM {
            get {
                return ResourceManager.GetString("SOCIALROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIALROOM_ANTENNA.
        /// </summary>
        internal static string SOCIALROOM_ANTENNA {
            get {
                return ResourceManager.GetString("SOCIALROOM_ANTENNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIALROOM_ANTENNA_CONSTRUCTION.
        /// </summary>
        internal static string SOCIALROOM_ANTENNA_CONSTRUCTION {
            get {
                return ResourceManager.GetString("SOCIALROOM_ANTENNA_CONSTRUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIALROOM_BILLARD.
        /// </summary>
        internal static string SOCIALROOM_BILLARD {
            get {
                return ResourceManager.GetString("SOCIALROOM_BILLARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIALROOM_BILLARD_BALLS.
        /// </summary>
        internal static string SOCIALROOM_BILLARD_BALLS {
            get {
                return ResourceManager.GetString("SOCIALROOM_BILLARD_BALLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIALROOM_BILLARD_BRUSH.
        /// </summary>
        internal static string SOCIALROOM_BILLARD_BRUSH {
            get {
                return ResourceManager.GetString("SOCIALROOM_BILLARD_BRUSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIALROOM_BILLARD_CHALK.
        /// </summary>
        internal static string SOCIALROOM_BILLARD_CHALK {
            get {
                return ResourceManager.GetString("SOCIALROOM_BILLARD_CHALK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIALROOM_BILLARD_CUE.
        /// </summary>
        internal static string SOCIALROOM_BILLARD_CUE {
            get {
                return ResourceManager.GetString("SOCIALROOM_BILLARD_CUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIALROOM_BILLARD_THINGS.
        /// </summary>
        internal static string SOCIALROOM_BILLARD_THINGS {
            get {
                return ResourceManager.GetString("SOCIALROOM_BILLARD_THINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIALROOM_BILLARD_TRIANGLE.
        /// </summary>
        internal static string SOCIALROOM_BILLARD_TRIANGLE {
            get {
                return ResourceManager.GetString("SOCIALROOM_BILLARD_TRIANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIALROOM_BOOKS.
        /// </summary>
        internal static string SOCIALROOM_BOOKS {
            get {
                return ResourceManager.GetString("SOCIALROOM_BOOKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIALROOM_CEILING.
        /// </summary>
        internal static string SOCIALROOM_CEILING {
            get {
                return ResourceManager.GetString("SOCIALROOM_CEILING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIALROOM_COUCH.
        /// </summary>
        internal static string SOCIALROOM_COUCH {
            get {
                return ResourceManager.GetString("SOCIALROOM_COUCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIALROOM_DARTS.
        /// </summary>
        internal static string SOCIALROOM_DARTS {
            get {
                return ResourceManager.GetString("SOCIALROOM_DARTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIALROOM_EAST_WALL.
        /// </summary>
        internal static string SOCIALROOM_EAST_WALL {
            get {
                return ResourceManager.GetString("SOCIALROOM_EAST_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIALROOM_GLASS_TABLE.
        /// </summary>
        internal static string SOCIALROOM_GLASS_TABLE {
            get {
                return ResourceManager.GetString("SOCIALROOM_GLASS_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIALROOM_MEDIASERVER.
        /// </summary>
        internal static string SOCIALROOM_MEDIASERVER {
            get {
                return ResourceManager.GetString("SOCIALROOM_MEDIASERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIALROOM_MONITOR.
        /// </summary>
        internal static string SOCIALROOM_MONITOR {
            get {
                return ResourceManager.GetString("SOCIALROOM_MONITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIALROOM_NORTH_WALL.
        /// </summary>
        internal static string SOCIALROOM_NORTH_WALL {
            get {
                return ResourceManager.GetString("SOCIALROOM_NORTH_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIALROOM_SEAT.
        /// </summary>
        internal static string SOCIALROOM_SEAT {
            get {
                return ResourceManager.GetString("SOCIALROOM_SEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIALROOM_SEATGROUP.
        /// </summary>
        internal static string SOCIALROOM_SEATGROUP {
            get {
                return ResourceManager.GetString("SOCIALROOM_SEATGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIALROOM_SOUTH_WALL.
        /// </summary>
        internal static string SOCIALROOM_SOUTH_WALL {
            get {
                return ResourceManager.GetString("SOCIALROOM_SOUTH_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIALROOM_WALL.
        /// </summary>
        internal static string SOCIALROOM_WALL {
            get {
                return ResourceManager.GetString("SOCIALROOM_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIALROOM_WEST_WALL.
        /// </summary>
        internal static string SOCIALROOM_WEST_WALL {
            get {
                return ResourceManager.GetString("SOCIALROOM_WEST_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPACE_LADDER.
        /// </summary>
        internal static string SPACE_LADDER {
            get {
                return ResourceManager.GetString("SPACE_LADDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPACE_SUIT.
        /// </summary>
        internal static string SPACE_SUIT {
            get {
                return ResourceManager.GetString("SPACE_SUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STAIRS.
        /// </summary>
        internal static string STAIRS {
            get {
                return ResourceManager.GetString("STAIRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STEPPER.
        /// </summary>
        internal static string STEPPER {
            get {
                return ResourceManager.GetString("STEPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STICKY_NOTE.
        /// </summary>
        internal static string STICKY_NOTE {
            get {
                return ResourceManager.GetString("STICKY_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TABLE.
        /// </summary>
        internal static string TABLE {
            get {
                return ResourceManager.GetString("TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOILET.
        /// </summary>
        internal static string TOILET {
            get {
                return ResourceManager.GetString("TOILET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOILET_SEAT.
        /// </summary>
        internal static string TOILET_SEAT {
            get {
                return ResourceManager.GetString("TOILET_SEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TREADMILL.
        /// </summary>
        internal static string TREADMILL {
            get {
                return ResourceManager.GetString("TREADMILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARDROBE.
        /// </summary>
        internal static string WARDROBE {
            get {
                return ResourceManager.GetString("WARDROBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WASHINGAREA.
        /// </summary>
        internal static string WASHINGAREA {
            get {
                return ResourceManager.GetString("WASHINGAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEIGHT_PLATES.
        /// </summary>
        internal static string WEIGHT_PLATES {
            get {
                return ResourceManager.GetString("WEIGHT_PLATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORKBENCH.
        /// </summary>
        internal static string WORKBENCH {
            get {
                return ResourceManager.GetString("WORKBENCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORKOUTS.
        /// </summary>
        internal static string WORKOUTS {
            get {
                return ResourceManager.GetString("WORKOUTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WRITING_MATERIALS.
        /// </summary>
        internal static string WRITING_MATERIALS {
            get {
                return ResourceManager.GetString("WRITING_MATERIALS", resourceCulture);
            }
        }
    }
}
