//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fenrir13.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Keys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Keys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fenrir13.Resources.Keys", typeof(Keys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIRLOCK.
        /// </summary>
        internal static string AIRLOCK {
            get {
                return ResourceManager.GetString("AIRLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIKE.
        /// </summary>
        internal static string BIKE {
            get {
                return ResourceManager.GetString("BIKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOTS.
        /// </summary>
        internal static string BOOTS {
            get {
                return ResourceManager.GetString("BOOTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BULKHEAD.
        /// </summary>
        internal static string BULKHEAD {
            get {
                return ResourceManager.GetString("BULKHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BULKHEAD_WINDOW.
        /// </summary>
        internal static string BULKHEAD_WINDOW {
            get {
                return ResourceManager.GetString("BULKHEAD_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARDIO_STATION.
        /// </summary>
        internal static string CARDIO_STATION {
            get {
                return ResourceManager.GetString("CARDIO_STATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARPET.
        /// </summary>
        internal static string CARPET {
            get {
                return ResourceManager.GetString("CARPET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAIR.
        /// </summary>
        internal static string CHAIR {
            get {
                return ResourceManager.GetString("CHAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAMBER_FLOOR.
        /// </summary>
        internal static string CHAMBER_FLOOR {
            get {
                return ResourceManager.GetString("CHAMBER_FLOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAMBER_WALL.
        /// </summary>
        internal static string CHAMBER_WALL {
            get {
                return ResourceManager.GetString("CHAMBER_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOCOLATEBAR.
        /// </summary>
        internal static string CHOCOLATEBAR {
            get {
                return ResourceManager.GetString("CHOCOLATEBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSET.
        /// </summary>
        internal static string CLOSET {
            get {
                return ResourceManager.GetString("CLOSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSET_DOOR.
        /// </summary>
        internal static string CLOSET_DOOR {
            get {
                return ResourceManager.GetString("CLOSET_DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMANDBRIDGE.
        /// </summary>
        internal static string COMMANDBRIDGE {
            get {
                return ResourceManager.GetString("COMMANDBRIDGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPUTER_TERMINAL.
        /// </summary>
        internal static string COMPUTER_TERMINAL {
            get {
                return ResourceManager.GetString("COMPUTER_TERMINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTROL_PANEL.
        /// </summary>
        internal static string CONTROL_PANEL {
            get {
                return ResourceManager.GetString("CONTROL_PANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTROL_PANEL_CONTENT.
        /// </summary>
        internal static string CONTROL_PANEL_CONTENT {
            get {
                return ResourceManager.GetString("CONTROL_PANEL_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORRIDOR_EAST.
        /// </summary>
        internal static string CORRIDOR_EAST {
            get {
                return ResourceManager.GetString("CORRIDOR_EAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORRIDOR_MID.
        /// </summary>
        internal static string CORRIDOR_MID {
            get {
                return ResourceManager.GetString("CORRIDOR_MID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORRIDOR_MIDEAST.
        /// </summary>
        internal static string CORRIDOR_MIDEAST {
            get {
                return ResourceManager.GetString("CORRIDOR_MIDEAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORRIDOR_MIDWEST.
        /// </summary>
        internal static string CORRIDOR_MIDWEST {
            get {
                return ResourceManager.GetString("CORRIDOR_MIDWEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORRIDOR_PAINTING.
        /// </summary>
        internal static string CORRIDOR_PAINTING {
            get {
                return ResourceManager.GetString("CORRIDOR_PAINTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORRIDOR_WEST.
        /// </summary>
        internal static string CORRIDOR_WEST {
            get {
                return ResourceManager.GetString("CORRIDOR_WEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CROSSTRAINER.
        /// </summary>
        internal static string CROSSTRAINER {
            get {
                return ResourceManager.GetString("CROSSTRAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRYOCHAMBER.
        /// </summary>
        internal static string CRYOCHAMBER {
            get {
                return ResourceManager.GetString("CRYOCHAMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRYOCHAMBER_DOOR.
        /// </summary>
        internal static string CRYOCHAMBER_DOOR {
            get {
                return ResourceManager.GetString("CRYOCHAMBER_DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRYOPOD.
        /// </summary>
        internal static string CRYOPOD {
            get {
                return ResourceManager.GetString("CRYOPOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISPLAY.
        /// </summary>
        internal static string DISPLAY {
            get {
                return ResourceManager.GetString("DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRAWER.
        /// </summary>
        internal static string DRAWER {
            get {
                return ResourceManager.GetString("DRAWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUMBBELL_BAR.
        /// </summary>
        internal static string DUMBBELL_BAR {
            get {
                return ResourceManager.GetString("DUMBBELL_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUMBBELL_RACK.
        /// </summary>
        internal static string DUMBBELL_RACK {
            get {
                return ResourceManager.GetString("DUMBBELL_RACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMPTYCREWCHAMBERONE.
        /// </summary>
        internal static string EMPTYCREWCHAMBERONE {
            get {
                return ResourceManager.GetString("EMPTYCREWCHAMBERONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMPTYCREWCHAMBERTWO.
        /// </summary>
        internal static string EMPTYCREWCHAMBERTWO {
            get {
                return ResourceManager.GetString("EMPTYCREWCHAMBERTWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENGINE_ROOM.
        /// </summary>
        internal static string ENGINE_ROOM {
            get {
                return ResourceManager.GetString("ENGINE_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQUIPMENT_BOX.
        /// </summary>
        internal static string EQUIPMENT_BOX {
            get {
                return ResourceManager.GetString("EQUIPMENT_BOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQUIPMENT_BOX_LOCK.
        /// </summary>
        internal static string EQUIPMENT_BOX_LOCK {
            get {
                return ResourceManager.GetString("EQUIPMENT_BOX_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQUIPMENT_ROOM.
        /// </summary>
        internal static string EQUIPMENT_ROOM {
            get {
                return ResourceManager.GetString("EQUIPMENT_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXERCISE_AREA.
        /// </summary>
        internal static string EXERCISE_AREA {
            get {
                return ResourceManager.GetString("EXERCISE_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FITNESSMACHINE.
        /// </summary>
        internal static string FITNESSMACHINE {
            get {
                return ResourceManager.GetString("FITNESSMACHINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRONTSIDE.
        /// </summary>
        internal static string FRONTSIDE {
            get {
                return ResourceManager.GetString("FRONTSIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRONTWINDOW.
        /// </summary>
        internal static string FRONTWINDOW {
            get {
                return ResourceManager.GetString("FRONTWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLOVES.
        /// </summary>
        internal static string GLOVES {
            get {
                return ResourceManager.GetString("GLOVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GYM.
        /// </summary>
        internal static string GYM {
            get {
                return ResourceManager.GetString("GYM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GYM_POWERSTATION.
        /// </summary>
        internal static string GYM_POWERSTATION {
            get {
                return ResourceManager.GetString("GYM_POWERSTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELMET.
        /// </summary>
        internal static string HELMET {
            get {
                return ResourceManager.GetString("HELMET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KITCHEN.
        /// </summary>
        internal static string KITCHEN {
            get {
                return ResourceManager.GetString("KITCHEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAPTOP.
        /// </summary>
        internal static string LAPTOP {
            get {
                return ResourceManager.GetString("LAPTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LATCH.
        /// </summary>
        internal static string LATCH {
            get {
                return ResourceManager.GetString("LATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MACHINE_CORRIDOR_MID.
        /// </summary>
        internal static string MACHINE_CORRIDOR_MID {
            get {
                return ResourceManager.GetString("MACHINE_CORRIDOR_MID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIRROR.
        /// </summary>
        internal static string MIRROR {
            get {
                return ResourceManager.GetString("MIRROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NECESSITIES.
        /// </summary>
        internal static string NECESSITIES {
            get {
                return ResourceManager.GetString("NECESSITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFFICECHAIR.
        /// </summary>
        internal static string OFFICECHAIR {
            get {
                return ResourceManager.GetString("OFFICECHAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTLINES.
        /// </summary>
        internal static string OUTLINES {
            get {
                return ResourceManager.GetString("OUTLINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVOID.
        /// </summary>
        internal static string OVOID {
            get {
                return ResourceManager.GetString("OVOID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARTITION_WALL.
        /// </summary>
        internal static string PARTITION_WALL {
            get {
                return ResourceManager.GetString("PARTITION_WALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEEPHOLE.
        /// </summary>
        internal static string PEEPHOLE {
            get {
                return ResourceManager.GetString("PEEPHOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERSONAL_SETTINGS.
        /// </summary>
        internal static string PERSONAL_SETTINGS {
            get {
                return ResourceManager.GetString("PERSONAL_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIERHOLE.
        /// </summary>
        internal static string PIERHOLE {
            get {
                return ResourceManager.GetString("PIERHOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PILOT_SEAT.
        /// </summary>
        internal static string PILOT_SEAT {
            get {
                return ResourceManager.GetString("PILOT_SEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYER.
        /// </summary>
        internal static string PLAYER {
            get {
                return ResourceManager.GetString("PLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTRAIT.
        /// </summary>
        internal static string PORTRAIT {
            get {
                return ResourceManager.GetString("PORTRAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RANK.
        /// </summary>
        internal static string RANK {
            get {
                return ResourceManager.GetString("RANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUBBER_ROLLS.
        /// </summary>
        internal static string RUBBER_ROLLS {
            get {
                return ResourceManager.GetString("RUBBER_ROLLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIALROOM.
        /// </summary>
        internal static string SOCIALROOM {
            get {
                return ResourceManager.GetString("SOCIALROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPACE_SUITE.
        /// </summary>
        internal static string SPACE_SUITE {
            get {
                return ResourceManager.GetString("SPACE_SUITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STEPPER.
        /// </summary>
        internal static string STEPPER {
            get {
                return ResourceManager.GetString("STEPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STICKY_NOTE.
        /// </summary>
        internal static string STICKY_NOTE {
            get {
                return ResourceManager.GetString("STICKY_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TABLE.
        /// </summary>
        internal static string TABLE {
            get {
                return ResourceManager.GetString("TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOILET.
        /// </summary>
        internal static string TOILET {
            get {
                return ResourceManager.GetString("TOILET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOILET_SEAT.
        /// </summary>
        internal static string TOILET_SEAT {
            get {
                return ResourceManager.GetString("TOILET_SEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TREADMILL.
        /// </summary>
        internal static string TREADMILL {
            get {
                return ResourceManager.GetString("TREADMILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARDROBE.
        /// </summary>
        internal static string WARDROBE {
            get {
                return ResourceManager.GetString("WARDROBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WASHINGAREA.
        /// </summary>
        internal static string WASHINGAREA {
            get {
                return ResourceManager.GetString("WASHINGAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORKBENCH.
        /// </summary>
        internal static string WORKBENCH {
            get {
                return ResourceManager.GetString("WORKBENCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORKOUTS.
        /// </summary>
        internal static string WORKOUTS {
            get {
                return ResourceManager.GetString("WORKOUTS", resourceCulture);
            }
        }
    }
}
