//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fenrir13.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locations {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locations() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Fenrir13.Resources.Locations", typeof(Locations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CRYOCHAMBER {
            get {
                return ResourceManager.GetString("CRYOCHAMBER", resourceCulture);
            }
        }
        
        internal static string CORRIDOR_EAST {
            get {
                return ResourceManager.GetString("CORRIDOR_EAST", resourceCulture);
            }
        }
        
        internal static string CORRIDOR_WEST {
            get {
                return ResourceManager.GetString("CORRIDOR_WEST", resourceCulture);
            }
        }
        
        internal static string CORRIDOR_MIDEAST {
            get {
                return ResourceManager.GetString("CORRIDOR_MIDEAST", resourceCulture);
            }
        }
        
        internal static string CORRIDOR_MID {
            get {
                return ResourceManager.GetString("CORRIDOR_MID", resourceCulture);
            }
        }
        
        internal static string CORRIDOR_MIDWEST {
            get {
                return ResourceManager.GetString("CORRIDOR_MIDWEST", resourceCulture);
            }
        }
        
        internal static string EMPTYCREWCHAMBERONE {
            get {
                return ResourceManager.GetString("EMPTYCREWCHAMBERONE", resourceCulture);
            }
        }
        
        internal static string EMPTYCREWCHAMBERTWO {
            get {
                return ResourceManager.GetString("EMPTYCREWCHAMBERTWO", resourceCulture);
            }
        }
        
        internal static string COMMANDBRIDGE {
            get {
                return ResourceManager.GetString("COMMANDBRIDGE", resourceCulture);
            }
        }
        
        internal static string COMPUTER_TERMINAL {
            get {
                return ResourceManager.GetString("COMPUTER_TERMINAL", resourceCulture);
            }
        }
        
        internal static string MACHINE_CORRIDOR_MID {
            get {
                return ResourceManager.GetString("MACHINE_CORRIDOR_MID", resourceCulture);
            }
        }
        
        internal static string GYM {
            get {
                return ResourceManager.GetString("GYM", resourceCulture);
            }
        }
        
        internal static string SOCIALROOM {
            get {
                return ResourceManager.GetString("SOCIALROOM", resourceCulture);
            }
        }
        
        internal static string KITCHEN {
            get {
                return ResourceManager.GetString("KITCHEN", resourceCulture);
            }
        }
        
        internal static string AIRLOCK {
            get {
                return ResourceManager.GetString("AIRLOCK", resourceCulture);
            }
        }
        
        internal static string ENGINE_ROOM {
            get {
                return ResourceManager.GetString("ENGINE_ROOM", resourceCulture);
            }
        }
        
        internal static string EQUIPMENT_ROOM {
            get {
                return ResourceManager.GetString("EQUIPMENT_ROOM", resourceCulture);
            }
        }
        
        internal static string AMBULANCE {
            get {
                return ResourceManager.GetString("AMBULANCE", resourceCulture);
            }
        }
        
        internal static string MAINTENANCE_ROOM {
            get {
                return ResourceManager.GetString("MAINTENANCE_ROOM", resourceCulture);
            }
        }
        
        internal static string JETTY {
            get {
                return ResourceManager.GetString("JETTY", resourceCulture);
            }
        }
        
        internal static string ROOF_TOP {
            get {
                return ResourceManager.GetString("ROOF_TOP", resourceCulture);
            }
        }
        
        internal static string PANEL_TOP {
            get {
                return ResourceManager.GetString("PANEL_TOP", resourceCulture);
            }
        }
    }
}
