//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fenrir13.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fenrir13.Resources.Locations", typeof(Locations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Kommando-Brücke|Kommando-Brücke|Brücke.
        /// </summary>
        internal static string COMMANDBRIDGE {
            get {
                return ResourceManager.GetString("COMMANDBRIDGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Computer-Terminal|Computer-Terminal|Computer|Terminal.
        /// </summary>
        internal static string COMPUTER_TERMINAL {
            get {
                return ResourceManager.GetString("COMPUTER_TERMINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der östliche Korridor|Korridor (ost).
        /// </summary>
        internal static string CORRIDOR_EAST {
            get {
                return ResourceManager.GetString("CORRIDOR_EAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mittlerer Korridor|Korridor (mitte).
        /// </summary>
        internal static string CORRIDOR_MID {
            get {
                return ResourceManager.GetString("CORRIDOR_MID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der mittel-östliche Korridor|Korridor (mitte-ost).
        /// </summary>
        internal static string CORRIDOR_MIDEAST {
            get {
                return ResourceManager.GetString("CORRIDOR_MIDEAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der mittel-westliche Korridor|Korridor (mitte-west).
        /// </summary>
        internal static string CORRIDOR_MIDWEST {
            get {
                return ResourceManager.GetString("CORRIDOR_MIDWEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der westliche Korridor|Korridor (west).
        /// </summary>
        internal static string CORRIDOR_WEST {
            get {
                return ResourceManager.GetString("CORRIDOR_WEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deine Cryo-Kammer|Cryo-Kammer|Cryokammer|Kammer.
        /// </summary>
        internal static string CRYOCHAMBER {
            get {
                return ResourceManager.GetString("CRYOCHAMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crew-Kammer-1.
        /// </summary>
        internal static string EMPTYCREWCHAMBERONE {
            get {
                return ResourceManager.GetString("EMPTYCREWCHAMBERONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crew-Kammer-2.
        /// </summary>
        internal static string EMPTYCREWCHAMBERTWO {
            get {
                return ResourceManager.GetString("EMPTYCREWCHAMBERTWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Fitnessraum|Fitnessraum|Trainingsraum|Gym.
        /// </summary>
        internal static string GYM {
            get {
                return ResourceManager.GetString("GYM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Maschinen-Korridor|Maschinen-Korridor|Maschinenkorridor.
        /// </summary>
        internal static string MACHINE_CORRIDOR_MID {
            get {
                return ResourceManager.GetString("MACHINE_CORRIDOR_MID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Sozialraum|Sozialraum|Aufenthaltsraum.
        /// </summary>
        internal static string SOCIALROOM {
            get {
                return ResourceManager.GetString("SOCIALROOM", resourceCulture);
            }
        }
    }
}
