//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fenrir13.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MetaData {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetaData() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Fenrir13.Resources.MetaData", typeof(MetaData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AUTHOR {
            get {
                return ResourceManager.GetString("AUTHOR", resourceCulture);
            }
        }
        
        internal static string COPYRIGHT {
            get {
                return ResourceManager.GetString("COPYRIGHT", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string VERSION {
            get {
                return ResourceManager.GetString("VERSION", resourceCulture);
            }
        }
        
        internal static string ASCII_TITLE {
            get {
                return ResourceManager.GetString("ASCII_TITLE", resourceCulture);
            }
        }
        
        internal static string QUEST_I {
            get {
                return ResourceManager.GetString("QUEST_I", resourceCulture);
            }
        }
        
        internal static string QUEST_II {
            get {
                return ResourceManager.GetString("QUEST_II", resourceCulture);
            }
        }
        
        internal static string QUEST_III {
            get {
                return ResourceManager.GetString("QUEST_III", resourceCulture);
            }
        }
        
        internal static string QUEST_IV {
            get {
                return ResourceManager.GetString("QUEST_IV", resourceCulture);
            }
        }
        
        internal static string QUEST_V {
            get {
                return ResourceManager.GetString("QUEST_V", resourceCulture);
            }
        }
        
        internal static string QUEST_VI {
            get {
                return ResourceManager.GetString("QUEST_VI", resourceCulture);
            }
        }
        
        internal static string QUEST_VII {
            get {
                return ResourceManager.GetString("QUEST_VII", resourceCulture);
            }
        }
        
        internal static string QUEST_VIII {
            get {
                return ResourceManager.GetString("QUEST_VIII", resourceCulture);
            }
        }
        
        internal static string QUEST_IX {
            get {
                return ResourceManager.GetString("QUEST_IX", resourceCulture);
            }
        }
        
        internal static string BETA_TESTER {
            get {
                return ResourceManager.GetString("BETA_TESTER", resourceCulture);
            }
        }
    }
}
