//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fenrir13.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OptionalVerbs {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OptionalVerbs() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Fenrir13.Resources.OptionalVerbs", typeof(OptionalVerbs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string DRIVE {
            get {
                return ResourceManager.GetString("DRIVE", resourceCulture);
            }
        }
        
        internal static string TRAIN {
            get {
                return ResourceManager.GetString("TRAIN", resourceCulture);
            }
        }
        
        internal static string PUT {
            get {
                return ResourceManager.GetString("PUT", resourceCulture);
            }
        }
        
        internal static string SCREW {
            get {
                return ResourceManager.GetString("SCREW", resourceCulture);
            }
        }
        
        internal static string SCREW_ON {
            get {
                return ResourceManager.GetString("SCREW_ON", resourceCulture);
            }
        }
        
        internal static string LEVER {
            get {
                return ResourceManager.GetString("LEVER", resourceCulture);
            }
        }
    }
}
